### ISSUE TITLE
Nouvelle interface web en développement

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#11]
Bonjour,

J'ai commencé il y a 2 jours à travailler sur l'interface web de CTparental.
Mais je rencontre quelques problèmes quant à son installation et son utilisation, en tout cas sous Ubuntu 14.04.

Par exemple, j'ai été « obligé » de supprimer une partie du code de CTparental.sh ligne 288 à 294 pour ne pas avoir l'erreur "error recovery network settings". L'installation se fait alors sans soucis.

Ça fonctionne, mais il y a quelques problèmes avec l'interface web, avec des « The connection was reset » par exemple.

Bref, déjà voici quelques images :
1. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161134.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161134.png)
2. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161153.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161153.png)
3. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161204.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161204.png)
4. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161214.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161214.png)
5. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161235.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_161235.png)

Je me demande si c'est bon endroit pour tout ça, merci de me le confirmer.

Librement

**Comment by cyberesprit** [comment]
Je rajoute des copies écrans concernant les pages de blocages et d'informations :

6. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_175956.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_175956.png)
7. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_180013.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_180013.png)
8. [https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_180023.png](https://cyberesprit.fr/temp/ctparental/Screenshot_20160412_180023.png)

Librement

**Comment by marsat** [comment]
Bonjour,
tous d'abord , super sympa interface.
Pour ce qui est de l'erreur ligne 288 à 294 , j'ai pas fait de test sous ubuntu dernièrement , je vais regarder sa.

pour « The connection was reset » cela proviens du faite que l'on relance dnsmasq , privoxy , et dansguardian pour que les changement soit prit en compte et que du cou cella provoque une coupure web momentané , je vais regarder ce que je peut faire de ce cotée , mais dans tous les cas, seul un utilisateur n'utilisant pas le proxy (non filtrée), pourras espérait ne pas a voir d'erreur de ce type.

**Comment by marsat** [comment]
j'ai modifier le script CTparental.sh pour permaitre , le verrouillage des comptes administrateurs de la machine ( groupe sudo et root ) dans l'interface web
![ctparental-interface10](https://cloud.githubusercontent.com/assets/6809414/14509993/85908236-01cf-11e6-8ce1-c01e4932f399.png)

https://github.com/marsat/CTparental/commit/9932a1a080bcf6bfc20f8ab5c51a48f7259cdfab

**Comment by cyberesprit** [comment]
> j'ai corigé le pb dans la 4.13-0
Merci, je vais testé ça rapidement !

> je n'est pas ce problème, quant j'administre avec un compte non filtrée
Moi si justement, avec le compte à l'installation d'ubuntu qui n'est donc pas filtré, ce message apparaît pour certaines actions dans l'administration, et ça pose d'autres problème derrières avec la session de l'interface web, un coup on est plus connecté mais si on rafraîchi la page on le redevient .. un peu compliqué à expliqué.

> j'ai modifier le script CTparental.sh pour griser des comptes administrateurs de la machine 
Ok pour cette modification, je vais voir avec la dernière version et adapté.

**Comment by marsat** [comment]
Bon j'ai regardais un peut , pour le problème , de déconne**x**ion  , je pense que cela venais du fait du paramétrage des variables system proxy a l'ouverture de session X , ce problème et normalement résolus dans la version 4.15-0.
pour l'aide en orthographe français et anglais  je suit preneur , car il et vrai que sur ce poins c'est vraiment la cata.  pour le code php , bash ... je suis juste un bricoleur donc aide bien venus aussi.

**Comment by cyberesprit** [comment]
Et nickel pour le résolution du problème de « The connection was reset » ! Merci.
J'ai testé après installation du nouveau paquet 4.15 avec ma version de l'interface web et tout est bon.

**Comment by cyberesprit** [comment]
L'interface web et la page de blocage sont disponibles au public.

Interface admin :
`git clone https://cyberesprit.fr/git/ctparental/CTadmin.git`

Page de blocage :
`git clone https://cyberesprit.fr/git/ctparental/CTparental.git`

**Comment by marsat** [comment]
peut tu ajouter dans tes lien git un copyright, que je puis mètre a jour celui du mien en même temps que la nouvelle interface .

https://github.com/marsat/CTparental/blob/master/debian/copyright

**Comment by cyberesprit** [comment]
Je préférerais mettre un copyleft avec une licence LPRAB mais bon .. D'ailleurs sur ce point, le licence GPL n'est pas reconnue en Europe (donc France), il y a la licence CECILL qui est similaire, peut-être que mettre ctparental sous double licence est une idée à prendre en compte ?

Je m'occupe du fichier, par contre je me fiche complètement qu'il y ai mon nom ou un truc qui m'identifie, donc c'est pas une obligation (sauf si c'est nécessaire pour une quelconque raison).

**Comment by cyberesprit** [comment]
C'est fait

**Comment by marsat** [comment]
j'ai tester un peut la nouvelle interface, j'ai u quelque bug notamment quant tu utilise `continue;` dans les dg_*.php tu n'incrémenter pas la variable ` $chknum = $chknum + 1;` , ce qui ne ce remarquer pas quant on décoche les case mais quant on recoche , sa provoquer un décalage dans les ligne et ne commenter pas la bonne ligne.

quelque problème aussi dans gctoff.php pour grisé les utilisateur administrateur du poste .

ainsi que dans hours.php , qui fonctionné mais sans les balise tableau avais une apparence toute caca. 

n'étant pas un pro , ya peut être de maïeur solution mais la tous fonctionne, en bien plus jolie grasse a toi , car moi je suis vraiment null pour ce qui est de la présentation ...

**Comment by cyberesprit** [comment]
Merci pour ces retours. Effectivement cette variable $chknum me dit quelque chose et il me semble l'avoir retirée parce-que je n'en voyait pas l'utilité, mais je ne suis plus sûr de moi.

ok pour ctoff.php.

Étrange pour hours.php, je vais regarder ça, on ne doit pas utiliser les tableau pour faire de mise en page, donc si en les omettant il y a des problèmes d'affichage, il y a un autre pb à régler ;-)

Le présentation est faite surtout grâce à bootstrap, il y en a d'autre, celle là est très bien (je trouve).

> j'ai aussi modifier les fichiers dansguardian pour , pour que sa corresponde avec le nouveau style.

Je ne sais pas ce que tu essaie de dire mais je vais regarder ça pour comprendre.

**Comment by marsat** [comment]
confDansgouardian/template.html
confDansgouardian/template-fr.html
qui correspondes, a la page de redirection **dansguardian** .
copier respectivement durent la procédure post installe dans 
/etc/dansguardian/languages/ukenglish/template.html
/etc/dansguardian/languages/french/template.html

www/CTparental/   étant la page de redirection **dnsmasq**.

pour tester cocher *ip  dans ***ip **ips ...** et essayer d’accéder a http://36.36.36.36

pour expliquer un peut mieux 

> j'ai aussi modifier les fichiers dansguardian pour , pour que sa corresponde avec le nouveau style.

**Comment by cyberesprit** [comment]
Salut,

Je viens d'installer CTparental sur un autre poste sous Ubuntu 16.04, donc le paquet pour Debian testing, et j'ai remarqué qu'il y a la « nouvelle » interface web ;-)

C'est cool !

Le code est suffisamment compréhensible ?

**Comment by marsat** [comment]
Oui , j'ai comprit le code de cette nouvelle interface du moins pour le php et le html , les parties en java, je les comprend pas trop , bien que j'ai bien comprit que c'est pour la mise en forme.

encore un grand merci a toi pour ta participation.

**Comment by cyberesprit** [comment]
De rien, avec plaisir ;-)

Par contre, c'est du javascript, et non java, ce n'est pas la même chose ...
Et oui c'est plus pour la mise en forme, il n'y a presque rien de  toute façon, jquery est utilisé par bootstrap pour les animations par exemple.
