### ISSUE TITLE
Corrections orthographiques

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#12]
Salut,

J'ai vu beaucoup (trop!) de fautes d'orthographe un peu partout (commentaires, code, nom de fichier ou dossier, variables, paquet deb, ...) que ce soit en français ou en anglais.

Je peux aider aussi dans ce sens. (Et je le veux !)

_Petite anectdote :_ Étrangement, c'est en français qu'on écrit « connexion » et en anglais qu'on écrit « connection » ;-)

**Comment by marsat** [comment]
dans ce but j'ai modifier le script et l'interface web pour qu'il utilise le même fichier locale il faudrait dans un premier temps , créé le fichier  locale/ctparental.pot avec un anglais correcte, chose que malheureusement je me sans incapable de faire , une foie ce fichier initial correctement créé je pourrai modifier les scriptes et interface en conséquence, il ne restera plus en suite qu'a créer les fichiers .po pour le français .

pour gérer les fichier .po , .pot et générer les .mo j'utilise Poedit `apt-get install poedit`.

**Comment by cyberesprit** [comment]
Je suis toujours là ;-)

Je peux m'occuper des deux langues sans problème.

Pour l'interface web, j'ai déjà remarqué qu'il y a eu des modification au niveau des fichiers de configuration (emplacement /etc). Je vais adapter tout ça.

Comment je peux te faire parvenir ma version ? (si ça t’intéresse bien entendu)

**Comment by marsat** [comment]
l'idéal c'est de Forker mon dépôt  , et de m’envoyer les modification sous forme de Pull requests.
du moins je pense car je suis pas encore un grand professionnel de git.

**Comment by cyberesprit** [comment]
Tu ne crée pas automatiquement un deb pour la 16.04 ? Je ne le trouve pas ici https://github.com/marsat/CTparental/releases/

**Comment by marsat** [comment]
pour ubuntu 16.04 c'est le même que pour debian testing

**Comment by cyberesprit** [comment]
Les corrections sont en cours, par contre il y a aussi les corrections en anglais, donc les phrases de base, il y aura il me semble le code à revoir.

**Comment by marsat** [comment]
oui c'est normal

**Comment by cyberesprit** [comment]
Salut, désolé mais je n'ai pas avancé sur cette partie, j'ai pour le moment trop de projets en cours (dont 1 surtout qui me prends trop de temps) donc je suis obligé de mettre celui là de côté, en espérant que ce soit temporaire.

**Comment by marsat** [comment]
Oui , on a pas 10 bras  :)) .

**Comment by marsat** [comment]
gros amélioration de ce coté, grasse a 
https://github.com/marsat/CTparental/pull/38
https://github.com/marsat/CTparental/pull/37

**Comment by marsat** [comment]
Microsoft acquiert GitHub! Merci à GitHub , mais je vais sur Gitlab. https://gitlab.com/marsat/CTparental

Microsoft acquires GitHub! Thanks to GitHub, but I'm going on Gitlab. https://gitlab.com/marsat/CTparental
