### ISSUE TITLE
Lisibilité du code

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#13]
Salut,

Pour modifier l'interface web de CTparental, j'ai donc lu le code, d'ailleurs j'ai un peu tout regarder (scripts bash, code php et html, et les fichiers du deb) et franchement il faut revoir tout ça.

Dans ma version actuelle, j'ai « nettoyé » le code au moins php, css et html, et j'en ai profité pour modifier quelques parties mineures.

Là aussi je peux aider, dans un premier temps pour un code plus lisible et rigoureux, et dans un second temps pour modifier/améliorer d'autres partie de code.

**Comment by marsat** [comment]
Microsoft acquiert GitHub! Merci à GitHub , mais je vais sur Gitlab. https://gitlab.com/marsat/CTparental

Microsoft acquires GitHub! Thanks to GitHub, but I'm going on Gitlab. https://gitlab.com/marsat/CTparental
