### ISSUE TITLE
Erreur compilation deb

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#14]
Salut,

Pendant ma tentative de compilation du deb depuis mon clone du dépôt git, j'ai eu 3 erreurs (sous ubuntu 14.04, machine virtuelle).
1. Il faut également installé le paquet « dbhelper » (à ajouter dans make-deb.txt)
2. C'était parcequ'il fallait configurer mon ~/.gitconfig
3. Par contre pour cette dernière je ne sais pas quoi faire :

```
gpg: « G*******e Marsat <g*******e.marsat@**********> » a été ignorée : la clef secrète n'est pas disponible
gpg: /tmp/debsign.v1HTieob/ctparental_4.14-0.dsc: clearsign failed: la clef secrète n'est pas disponible
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1293:
running debsign failed
gbp:error: 'debuild -i -I' failed: it exited with 29
```

Une idée ?

**Comment by marsat** [comment]
pour
gbp:error: 'debuild -i -I' failed: it exited with 29
j'ai pas encore trouvé de solution , mais le deb et malgré tous bien crée ? du cous je comprend encore moins.
je chercherai un peut plus quand j'aurai du temps.

**Comment by cyberesprit** [comment]
Je suppose que c'est lié aux lignes du dessus qui concerne la signature ?
Oui le paquet est effectivement créé, je n'avais pas vu que c'était dans le dossier build-area.

Je vais le tester.

**Comment by cyberesprit** [comment]
Il y a maintenant une erreur dans le fichier make-deb.txt, pour Ubuntu il faut déplacer debhelper 3 lignes au dessus ;-)

**Comment by cyberesprit** [comment]
Autre chose, à l'installation du paquet je vois qu'il y a des fichiers/dossiers en doublon, par exemple pour le dossier www contenant les pages web CTadmin et CTparental, elles sont à la fois dans /var/www (celles réellement utilisées) et dans /usr/local/share/CTparental/www.

Est-ce normal/utile ?

**Comment by cyberesprit** [comment]
L'installation du nouveau paquet en tout cas sous ubuntu 14.04 fonctionne à merveille.

Juste un truc qu'il y avait déjà : Au moment de demander l'identifiant, ça nous force à avoir au moins un chiffre, ça ne devrait concerner que le mot de passe non ?

**Comment by marsat** [comment]
je regard sa oui normalement , cela ne doit pas forcer les nombres sur l'identifiant , juste les autorisé.
je corrige sa ...

si non pour le problème 
gbp:error: 'debuild -i -I' failed: it exited with 29 
c'est effectivement une histoire de signature de paquet, j'ai modifier le make-deb.txt pour corrigée cette erreur.

**Comment by marsat** [comment]
l'interface et effectivement mise dans /usr/local/share/CTparental/www par le deb
et seulement en suite copier dans /var/www  par le scripte de postinst qui exécute la commande
/usr/local/bin/CTparental.sh -i -nodep -nomanuel 
c'est utile car cela permet de réstorer l'interface d'origine en cas ou l'utilisateur l'aurai personalisée.
en lancent un CTparental.sh -uhtml

**Comment by cyberesprit** [comment]
Ha oui d'accord je vois, merci.

**Comment by marsat** [comment]
bon je suis arrivé a quelque chose pour les erreurs de génération de paquet, il ne reste plus que ces 3 la 
W: ctparental source: newer-standards-version 4.16.2 (current is 3.9.7)
W: ctparental: binary-without-manpage usr/bin/CTparental
W: ctparental: binary-without-manpage usr/bin/CTparental-bl-infos

dans ce commit https://github.com/marsat/CTparental/commit/ba4e9b060b15c03c6baba6b44b7803ba732e8ead

par contre j'ai du migrer les fichiers de conf dans /etc/CTparental et supprimer les extensions des scriptes .sh.

**Comment by marsat** [comment]
après un petit ménage , on arrive a 
`Now running lintian...
E: ctparental source: source-is-missing www/CTadmin/js/bootstrap.min.js
E: ctparental source: source-is-missing www/CTadmin/js/jquery-1.12.3.min.js
E: ctparental source: source-is-missing www/CTparental/js/bootstrap.min.js
E: ctparental source: source-is-missing www/CTparental/js/jquery-1.12.3.min.js
W: ctparental source: changelog-should-mention-nmu
W: ctparental source: newer-standards-version 4.18.5 (current is 3.9.8)
W: ctparental: manpage-has-useless-whatis-entry usr/share/man/man1/CTparental.1.gz
W: ctparental: binary-without-manpage usr/bin/CTparental-bl-infos
Finished running lintian.
`
les erreur sur les .js sont faut positif a mon avis.
pour le reste , encore des modification sur les man .

**Comment by marsat** [comment]
Microsoft acquiert GitHub! Merci à GitHub , mais je vais sur Gitlab. https://gitlab.com/marsat/CTparental

Microsoft acquires GitHub! Thanks to GitHub, but I'm going on Gitlab. https://gitlab.com/marsat/CTparental
