### ISSUE TITLE
CTparental via réseau

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#15]
Est-il possible d'installer CTparental sur un serveur et de s'en servir comme proxy ? J'imagine que ça ne correspond pas en tout cas avec les filtres par utilisateurs ....

Si non, j'imagine qu'il serait possible de synchroniser la configuration de plusieurs clients (entre eux ou depuis un serveur [rsync, syncthing, puppet, ...]) pour éviter de devoir faire chaque modifications sur chaque machines clientes ?

Des idées ?

**Comment by marsat** [comment]
oui en synchronisent avec rsync, cela doit être possible.
Mais pour un petit nombre de postes ,sinon l'utilisation d'outils comme http://www.alcasar.net/ dont je me suis inspirée pour CTparental, me semble plus approprié. 
l'idéal ce serai un Alcasar sous Debian , mais c'est un sacré boulot pour arriver a tous adapté.

**Comment by marsat** [comment]
début de piste pour la synchro de plusieurs postes, basé sur rsync et ssh avec un compt appartement au group sudo et shadow, une autentification par clef public clef privée .
le tout lancer dan un cron , manque surrement plein de chause mais c'est un debus.
```
ipMaskValide() {
ip=$(echo "$1" | cut -d"/" -f1)
mask=$(echo "$1" | grep "/" | cut -d"/" -f2)
if [ "$(echo "$1" | grep -c "^\(\(2[0-5][0-5]\|2[0-4][0-9]\|1[0-9][0-9]\|[0-9]\{1,2\}\)\.\)\{3\}\(2[0-5][0-5]\|2[0-4][0-9]\|1[0-9][0-9]\|[0-9]\{1,2\}\)$")" -eq 1 ];then
	echo 1
	return 1
fi
if [ ! "$(echo "$ip" | grep -c "^\(\(2[0-5][0-5]\|2[0-4][0-9]\|1[0-9][0-9]\|[0-9]\{1,2\}\)\.\)\{3\}\(2[0-5][0-5]\|2[0-4][0-9]\|1[0-9][0-9]\|[0-9]\{1,2\}\)$")" -eq 1 ];then
	echo 0
	return 0
fi
if [ "$(echo "$mask" | grep -c "^\([1-9]\|[1-2][0-9]\|3[0-2]\)$")" -eq 1 ];then
	echo 1
	return 1
fi
i=1 
octn=255
result=1
while [ $i -le 4 ]
do
oct=$( echo "$mask" | grep '\.'| cut -d "." -f$i )
if [ -z "$oct" ] ; then
	result=0
	break
fi
if [ ! "$octn" -eq 255 ];then
	if [ ! "$oct" -eq 0 ];then
		result=0
		break
	fi
fi 
octn=$oct
if [ ! "$oct" -eq 255 ] &&  [ ! "$oct" -eq 254 ]  &&  [ ! "$oct" -eq 252 ] &&  [ ! "$oct" -eq 248 ] &&  [ ! "$oct" -eq 240 ] &&  [ ! "$oct" -eq 224 ] &&  [ ! "$oct" -eq 192 ] &&  [ ! "$oct" -eq 128 ] &&  [ ! "$oct" -eq 0 ]; then
	result=0
	break	
  fi
i=$(( i + 1 ))
done
   echo $result
   return $result
}

ip_route="$(ip route)"
interface_WAN="$(awk '{print $5}' <<< ${ip_route})" # GW!
if [ "$(ifconfig | grep -c "adr" )" -ge 1 ];then 
	## jessie et infèrieur
	ipinterface_WAN="$(ifconfig "$interface_WAN" | awk '/adr:/{print substr($2,5)}')"
else
	## testing/sid
	ipinterface_WAN="$(ifconfig "$interface_WAN" | awk '/inet /{print substr($2,1)}')"
fi
reseau_box="$(awk '/'"${ipinterface_WAN}"'/{print $10}' <<< ${ip_route})"
if [ "$reseau_box" = "$interface_WAN" ];then # cat de mageia mais peut ètre dans d'autres aussi
reseau_box="$(awk '/'"${ipinterface_WAN}"'/{print $8}' <<< ${ip_route})"
fi

if [ "$( ipMaskValide "$reseau_box" )" -eq 0 ];then
gettext 'error recovery network settings'
echo
exit 1
fi 

PCinNETWORK=$(fping -q -c 1 -t 60 -g "$reseau_box" 2>&1 |  grep "1/1/0" | awk '{print $1}')
for ip in $PCinNETWORK ; do
RSYNC=/usr/bin/rsync
SSH=/usr/bin/ssh
KEY=/home/backupuser/.ssh/private/rsync-key
RUSER=backupuser #ajouter le dans le group sudo et shadow et autoriser le a lancer ce scripte en root sans sans mot de passe.
RHOST=$ip
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/CTparental /etc/CTparental 
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/dansguardian/lists/bannedsitelist /etc/dansguardian/lists/bannedsitelist
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/dansguardian/lists/bannedmimetypelist /etc/dansguardian/lists/bannedmimetypelist
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/dansguardian/lists/bannedextensionlist /etc/dansguardian/lists/bannedextensionlist
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/passwd /etc/passwd
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/shadow /etc/shadow
$RSYNC -auz -e "$SSH -i $KEY" $RUSER@$RHOST:/etc/group /etc/group

done
```

**Comment by cyberesprit** [comment]
Salut,

Merci pour ce retour. Je me demande quelle est la meilleure solution :

1. Intégrer la synchronisation entre machines dans ctparental,
2. Utiliser ou créer un service spécifique, ce qui permet par la suite de s'en servir pour tout un tas d'autre applications.

Je n'ai pas encore de temps pour ça (mais j'espère bientôt) mais j'ai déjà cogité pour la 2ème proposition, ça m'a l'air faisable.

**Comment by cyberesprit** [comment]
Par  contre je suis du genre à vouloir me passer de serveur, et d'abuser de réseau et programme distribué (contre centralisé et décentralisé), peu importe le nombre de machine, donc Alcasar ou autre basé sur un serveur, je vais éviter ;-)

On est loin de ce but pour la majorité des outils mais ça vient doucement (syncthing par exemple).

**Comment by marsat** [comment]
oui je trouve a mieux pour des petite structure pas besoins de maintenir un serveur pour 10 postes :)
