### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#16]
Salut,

Ubuntu 16.04 va sortir en fin de semaine, j'ai testé le deb généré en version 4.15 mais évidemment ça ne fonctionne pas convenablement.

Premièrement, en faisant donc « sudo dpkg -i ctparental_4.15-0_all.deb », il me marque ceci :

```
Sélection du paquet ctparental précédemment désélectionné.
(Lecture de la base de données... 206860 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de ctparental_4.15-0_all.deb ...
Dépaquetage de ctparental (4.15-0) ...
dpkg: des problèmes de dépendances empêchent la configuration de ctparental :
 ctparental dépend de dnsmasq ; cependant :
  Le paquet dnsmasq n'est pas installé.
 ctparental dépend de lighttpd ; cependant :
  Le paquet lighttpd n'est pas installé.
 ctparental dépend de php5-cgi ; cependant :
  Le paquet php5-cgi n'est pas installé.
 ctparental dépend de iptables-persistent ; cependant :
  Le paquet iptables-persistent n'est pas installé.
 ctparental dépend de dansguardian ; cependant :
  Le paquet dansguardian n'est pas installé.
 ctparental dépend de privoxy ; cependant :
  Le paquet privoxy n'est pas installé.
 ctparental dépend de libnss3-tools ; cependant :
  Le paquet libnss3-tools n'est pas installé.
 ctparental dépend de console-data ; cependant :
  Le paquet console-data n'est pas installé.

dpkg: erreur de traitement du paquet ctparental (--install) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 ctparental
```

Et deuxièmement, ce n'est plus php5 mais php7, le paquet « php5-cgi » n'existe donc pas, il peut être remplacé simplement par « php-cgi » ou au pire par « php7.0-cgi ».

Pour le 1er cas, je crois que j'ai eu le même problème en 15.10, il faut donc les installer à la main mais c'est normal je crois avec ma commande d'installation du paquet, je ne sais plus si il y a une option pour gérer les dépendances avec dpkg.

**Comment by marsat** [comment]
avec **dpkg** il n'y a pas de gestion des dépendance il faut utilisée **gdebi** pour sa
pour avoir la commande gdebi sans l'interface graphique c'est apt-get install gdebi-core

si non pour php j'ai créer un deb pour ubuntu 16.04 
https://github.com/marsat/CTparental/releases/download/4.16.3/ctparental_ubuntu_16.0_4.16.3-1_all.deb

**Comment by cyberesprit** [comment]
Merci pour les infos. Et pour le paquet.
Ce paquet ne fonctionne que pour 16.04 ou aussi pour les versions précédentes ?

**Comment by cyberesprit** [comment]
Il y a un souci à l'installation sur 16.04 :


```
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Controle parental.
 Filtrage web basé sur dnsmasq, lighttpd et cron,
 une gestion des horaires de connection est aussi intégrée et
 une interface web (http://127.0.0.1/CTadmin) permettant de paramétrer tous ça.
 Le couple login mot de passe doit être saisi à l'install, mais peut être
 modifié par la suite grâce à la commande CTparental.sh -uhtml.
Voulez-vous installer le paquet logiciel ? [o/N] :o
Sélection du paquet ctparental précédemment désélectionné.
(Lecture de la base de données... 208344 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de ctparental_ubuntu_16.0_4.16.3-1_all.deb ...
Dépaquetage de ctparental (4.16.3-1) ...
Paramétrage de ctparental (4.16.3-1) ...
cat: '/etc/apt/sources.list.d/*': Aucun fichier ou dossier de ce type
<iptablesreload>
iptables-persistent: unrecognized service
<updatecauser>
certutil:  unable to open "/var/www/CTparental/cactparental.crt" for reading (-5950, 2).
</updatecauser>
</iptablesreload>
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
attente de connexion au serveur de Toulouse:.......................................connexion au serveur de Toulouse impossible.dpkg: erreur de traitement du paquet ctparental (--install) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 ctparental
```

En fait à ce moment, mon fichier /etc/resolv.conf contient :

`nameserver 127.0.0.1`

Et plus :

`nameserver 192.168.1.1`

qui est ma passerelle Internet.

Une idée ?

**Comment by marsat** [comment]
j'ai regardé de plus prés ton problème, sur la dernière verssion tous samble bien fonctionné, même sur ubuntu 16.04 .
https://github.com/marsat/CTparental/releases/tag/4.16.4
avant de tenté de l'installer désinstalle, l'ancienne version comme ceci.
sudo apt-get autoremove --purge ctparental clamav-* 
sudo sed -i "s?^%ctoff.*??g" /etc/sudoers
sudo sed -i "s?^ALL  ALL=(ALL) NOPASSWD:/usr/local/bin/CTparental.sh.*??g" /etc/sudoers
redémarre le pc vérifie, que tu a bien accès a internet avans de réinstaller la nouvel version, si ce n'est pas le cas il faut en premier régler ce problème.

**Comment by cyberesprit** [comment]
Super je vais tester tout ça !

J'utilise bien gdebi ;-)

`sudo gdebi ctparental_ubuntu_16.04_4.16.4-1_all.deb`

**Comment by cyberesprit** [comment]
Ça fonctionne, il m'a quand même modifié mon /etc/resolv.conf, donc j'ai pu le modifier le temps qu'il cherchait à joindre Toulouse et c'est bon, mais pour confirmer ce pb je re-testerais plus tard sur une installation toute neuve.

Par contre, est-ce que les erreurs suivantes posent problème ?

`iptables-persistent: unrecognized service`

`Job for dansguardian.service failed because a configured resource limit was exceeded. See "systemctl status dansguardian.service" and "journalctl -xe" for details.`

`certutil:  unable to open "/var/www/CTparental/cactparental.crt" for reading (-5950, 2).
`

`cat: '/etc/apt/sources.list.d/*': Aucun fichier ou dossier de ce type`

**Comment by marsat** [comment]
`iptables-persistent: unrecognized service` est un problème auquel je n'avai pas fait attention en effet dans ubuntu 16.04 le service i`ptables-persistent `a étais renommé en `netfilter-persistent` comme sous debian du cout plus aucune différence entre le paquet debian testing/sid et celui pour ubuntu 16.04 , il convient d'onc 'utilisé le paquet pour debian testing pour ubuntu 16.04.
https://github.com/marsat/CTparental/releases/download/4.16.4/ctparental_debian_testing_4.16.4-1_all.deb

l'erreur `Job for dansguardian.service failed because a configured resource limit was exceeded. See "systemctl status dansguardian.service" and "journalctl -xe" for details.` est normale l'aure de l’installation , mais doit disparaître après a testés avec un `service dansguardian restart `

 pour certutil , faut que approfondissement mais rien de grave a priori.

`cat: '/etc/apt/sources.list.d/*': Aucun fichier ou dossier de ce type` sa c'est tous a fait normal si tu n'a pas de fichier de depot personnalisée dans le répertoir /etc/apt/sources.list.d/ , mais cela n'a strictement aucune incidence.

**Comment by marsat** [comment]
`certutil: unable to open "/var/www/CTparental/cactparental.crt" for reading (-5950, 2).`
c'est normal en début  d'installation  , en effet la fonction **iptablesreload** fait appelle a la fin a la fonction **updatecauser** mais  les certificats ne sont pas encore générais , cette erreur disparité une foie l'installation terminée.
je patch la fonction   **iptablesreload** pour que cette erreur disparaisse dans les prochaine version.

**Comment by marsat** [comment]
ci-dessous ma dernière installe via gdebi  , plus d'erreur :)
tester sous debian testing/sid et ubuntu 16.04

`
$ sudo gdebi ctparental_debian_testing_4.16.5-1_all.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Controle parental.
 Filtrage web basé sur dnsmasq, lighttpd et cron,
 une gestion des horaires de connection est aussi intégrée et
 une interface web (http://127.0.0.1/CTadmin) permettant de paramétrer tous ça.
 Le couple login mot de passe doit être saisi à l'install, mais peut être
 modifié par la suite grâce à la commande CTparental.sh -uhtml.
Voulez-vous installer le paquet logiciel ? [o/N] :o
Sélection du paquet ctparental précédemment désélectionné.
(Lecture de la base de données... 156395 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de ctparental_debian_testing_4.16.5-1_all.deb ...
Dépaquetage de ctparental (4.16.5-1) ...
Paramétrage de ctparental (4.16.5-1) ...
<iptablesreload>
[....] Saving netfilter rules...run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
done.
</iptablesreload>
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
Waiting to Connect to Server from Toulouse:
connection established:--2016-04-20 23:37:28--  http://dsi.ut-capitole.fr/blacklists/download/blacklists.tar.gz
Résolution de dsi.ut-capitole.fr (dsi.ut-capitole.fr)… 193.49.48.249
Connexion à dsi.ut-capitole.fr (dsi.ut-capitole.fr)|193.49.48.249|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 7290790 (7,0M) [application/x-gzip]
Sauvegarde en : « /tmp/alcasar/blacklists.tar.gz »

     0K .......... .......... .......... .......... ..........  0%  487K 15s
   ...
  7000K .......... .......... .......... .......... .......... 99% 2,19M 0s
  7050K .......... .......... .......... .......... .......... 99% 2,17M 0s
  7100K .......... .........                                  100% 2,11M=3,6s

2016-04-20 23:37:32 (1,96 MB/s) — « /tmp/alcasar/blacklists.tar.gz » sauvegardé [7290790/7290790]

adapt
23:37:32
<dnsmasqoff>
<resolvconffixoff>
</resolvconffixoff>
</dnsmasqoff>
blacklist and WhiteList , migration process. Please wait : .........................................................
23:37:43
<catChoice>
</catChoice>
<reabdomaine>
23:37:43

Application whitelisting (restored area):...................
23:37:48
</reabdomaine>
<dnsmasqon>
<resolvconffixon>
</resolvconffixon>
</dnsmasqon>
<confdansguardian>
</confdansguardian>
<confprivoxy>
</confprivoxy>
<FoncHTTPDCONF>
<CActparental>
Signature ok
subject=/C=FR/ST=FRANCE/L=ici/O=ctparental/CN=localhost
Getting CA Private Key
Signature ok
subject=/C=FR/ST=FRANCE/L=ici/O=ctparental/CN=duckduckgo.com
Getting CA Private Key
Signature ok
subject=/C=FR/ST=FRANCE/L=ici/O=ctparental/CN=search.yahoo.com
Getting CA Private Key
<updatecauser>
</updatecauser>
</CActparental>
</FoncHTTPDCONF>
<activegourpectoff>
groupadd : le groupe « ctoff » existe déjà
0
Ajout de l'utilisateur root au groupe ctoff
Retrait de l'utilisateur nobody du groupe ctoff
Retrait de l'utilisateur child du groupe ctoff
</activegourpectoff>
<iptablesreload>
[....] Saving netfilter rules...run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
done.
<updatecauser>
</updatecauser>
</iptablesreload>
`
