### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ZikyHD** [marsat/CTparental#18]
I have a permission issue on CTparental.

Each time i try to modify categories on blacklist or whitelist with the web interface, i could read the message:
"Erreur d'ouverture du fichier /etc/CTparental/categories-enabled.conf" and my changes aren't not saved.
The file domaine-rehabiliter.conf can be modified because my changes are saved.

It's probably nothing but the result is i can't activate filters for my child :/

Thank you for your help...

**Comment by marsat** [comment]
it is fixed in this commit
https://github.com/marsat/CTparental/commit/fc2cb188a1031b07033dc9bd46af2d83fd77d997

but if you do not want  to waith for the next one releases , you can do it in root.
`CTparent -uhtml`
sorry for my English.

**Comment by ZikyHD** [comment]
Thank you for your quick answer. I m using edubuntu 16.04. I ve installed CTparental from the deb file. I ll try your fix and tell you if it works

**Comment by ZikyHD** [comment]
I'm using ctparental_debian_testing_4.16.5-1_all.deb. I'm trying to install from source instead...

**Comment by ZikyHD** [comment]
I try your fix without success :/ In fact i was trying to activate whitelist only on CTparental.
I tried to activate it with `CTparental -cble` but for blacklist and whitelist, when i selected O or N to the first category, the script just waited.
First i've edited CTparental.conf to force DNSMASQ=WHITE without success.
I've seen on code there was reading the categories enabled so i added category "child" and force DNSMASQ=WHITE again. Then it works! It's quite dirty  i admit it ...

**Comment by marsat** [comment]
I solved the loop For troubleshooting when you execute CTparental -cble in the latest releases.
thank you for this bug back.
