### ISSUE TITLE
error recovery network settings

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#19]
Salut,

Je viens de tenter l'installation de la dernière version actuelle de ctparental sur une distribution basé sur ubuntu 14.04 (elementaryos) mais j'ai cette erreur :

```
Preparing to unpack ctparental_ubuntu_14.04_4.16.7-1.0_all.deb ...
Unpacking ctparental (4.16.7-1.0) ...
Paramétrage de ctparental (4.16.7-1.0) ...
error recovery network settings
dpkg: error processing package ctparental (--install):
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 ctparental
```

Il me semblait l'avoir déjà eu cette erreur. Une idée ?

**Comment by marsat** [comment]
je regarde sa, sa viens a priori  d'un problème dans la détection des périphériques réseaux.

**Comment by marsat** [comment]
je viens de me monter , une xubuntu 14.04 dans une vbox pour tester .
mais j'ai pas eu ce problème a l'install , juste une erreur de service netfilter-persistent save qui n'existe pas  j'ai corriger  le paquer pour cet erreur ctparental_ubuntu_14.04_4.16.7-1.1_all.deb, mais il faut bien répondre Y a cette question.
```
   Fichier de configuration '/etc/CTparental/dist.conf'
   ==> Supprimé (par vous-même ou par un script) depuis l'installation.
   ==> Le distributeur du paquet a fourni une version mise à jour.
   Que voulez-vous faire ? Vos options sont les suivantes :
    Y ou I  : installer la version du responsable du paquet
    N ou O  : garder votre version actuellement installée
      D     : afficher les différences entre les versions
      Z     : suspendre ce processus pour examiner la situation
 L'action par défaut garde votre version actuelle.
*** dist.conf (Y/I/N/O/D/Z) [défaut=N] ? Y
```

pour t'on erreur j'ai pas réussi a la reproduire , il me faudrait le retour des commandes suivantes pour y voir plus clair:

`sudo ip route`

`sudo ifconfig`

**Comment by marsat** [comment]
je viens juste d'installer elementaryos-0.3.2-stable-amd64.20151209 en vbox et j'ai bien le même problème , je regarde sa dans la soirée si j'ai un peut de temps.

**Comment by cyberesprit** [comment]
J'imagine donc que tu n'as pas besoin de mes retours de commandes mais je le fait quand même :

```
$ sudo ip route 
default via 192.168.1.1 dev eth0  proto static 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.50  metric 1 

$ sudo ifconfig
eth0      Link encap:Ethernet  HWaddr 5c:26:0a:63:f0:66  
          inet addr:192.168.1.50  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::5e26:aff:fe63:f066/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:73174 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53028 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:75636506 (75.6 MB)  TX bytes:6052776 (6.0 MB)
          Interrupt:20 Memory:e2e00000-e2e20000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:29131 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29131 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:5536711 (5.5 MB)  TX bytes:5536711 (5.5 MB)

wlan0     Link encap:Ethernet  HWaddr a0:88:b4:2d:ee:c4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Par contre au moment des faits la connexion active était wlan0 et non eth0.

**Comment by cyberesprit** [comment]
Je me souviens, j'ai eu le même problème au début sous ubuntu unity, je ne me souviens plus de la version. J'avais testé simplement en commentant la condition qui génère ce message, et ça passe.

Maintenant, est-ce que tout fonctionne et est-ce que tout est bien installé, je ne sais pas, j'ai au moins l'accès à l'admin qui fonctionne ;-)

**Comment by marsat** [comment]
problème résolut dans cette version: https://github.com/marsat/CTparental/releases/download/4.16.8/ctparental_ubuntu_14.04_4.16.8-1.1_all.deb

faudra bien désinstaller la version précédent , en effacent /etc/CTparental/CTparental.conf

**Comment by cyberesprit** [comment]
cool Merci, apparemment ça fonctionne à merveille !
