### ISSUE TITLE
Test sous Linux Mint

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#20]
Salut,

Juste parce-que je teste différentes distributions, j'ai installé ctparental sous Linux Mint 17.2 cinnamon.
L'installation de la version pour ubuntu 14.04 (car base ubuntu) à l'air de bien se passer.

L'accès à l'interface d'admin est ok.

Par contre, tout est bloqué par défaut pour les utilisateurs qui sont filtrés.
J'ai désactivé ctparental, et là c'est bon.
Je l'ai ré-activé, là c'était bon jusqu'à ce qu'il me bloque un site de test qui doit être bloqué : après ça tout est re-bloqué.

C'est juste pour information car je ne penses pas resté sur Mint pour l'école.

**Comment by marsat** [comment]
je viens de tester avec la version Mint 17.3 amd64, j'ai pas encore constater de problème du moins avec la dernière version de ctparental, si ce n'est qu'il fait valider les certificat , pour les redirection safe duckduckgo  dans chaque profile utilisateur filtrée.

install avec le deb pour ubuntu 14.04, via gdebi bien sur.
