### ISSUE TITLE
Raspbian erreur de récupération des parametres réseaux

### ISSUE THREAD

**Issue by ersplus** [marsat/CTparental#21]
Bonjour et merci pour ce projet.
Lors de l'installation de ctparental jessie 4.18.1-1 sur une distribution raspbian pour RPi3, l'installation par gdebi se déroule correctement, login et mdp, puis l'erreur suivante apparait : 
`erreur de récupération des paramètres réseaux`
interfaces
```
auto lo 
iface lo inet loopback
iface eth0 inet dhcp
allow-hotplug wlan0
iface wlan0 inet manual
wpa-conf /etc/wpa_supplicant.conf
```

resolv.conf
```
# Generated by resolvconf
domain internetxxxx.fr
nameserver 127.0.0.1
```

J'ai beau nettoyer par 
apt-get  autoremove --purge ctparental clamav-*

Je ne vois vraiement pas pourquoi cela ne fonctionne pas... Pouvez vous m'éclairer ?

En vous remerciant par avance

**Comment by marsat** [comment]
bonjour,
tous d'abord merci pour l’intérêt  que vous porté a mon projet , le problème viens sûrement, de la manière d'on la commande ifconfig ou ip route répond.

il faut en suite modifier les ligne 230 a 251 du scripte CTparental en conséquance.

si tu ne te sent pas de faire cet modification poste ici le retour des commandes suivantes en root:
`ip route`
`ifconfig`

**Comment by ersplus** [comment]
Bonjour et merci de votre réponse,

Pour ce qui est du paramétrage de la connexion internet, je ne pense pas que cela vienne de là (testé plusieurs fois sur d'autres config)
Plutôt la manière dont les commandes répondent. la version 0.17.1 fonctionnait ou bien est ce du à une mises a jour Debian.

J'avais identifié les lignes mais malheureusement je n'ai pas trouvé d'issue au problème. En ce sens, une aide est la bienvenue ;-)

Encore merci pour votre projet !

[ifconfig.txt](https://github.com/marsat/CTparental/files/385905/ifconfig.txt)
[iproute.txt](https://github.com/marsat/CTparental/files/385904/iproute.txt)

**Comment by marsat** [comment]
j'ai modifier le scripte en fonction des tes raiponces **ip route** et **ifconfig** ,cela devrai fonctionner en appliquant les changement du lien ci dessous.
https://github.com/marsat/CTparental/compare/4.18.1...master

merci de me dir si cela fonctionne   , je validerais ce correctif dans les prochaine version.

**Comment by ersplus** [comment]
Je viens de faire deux tests, un sur le RPi3 et un sur une VM Debian 8.5 brute. Dans les deux cas l'erreur persiste. Voulez vous les fichiers de configuration de la VM Debian 8.5 aussi ? au cas ou ?

Je ne suis pas un crack et je sais pas bien scripter, mais un truc du genre : ip route get 8.8.8.8
8.8.8.8 via 192.168.1.1 dev ....
ou 192.168.1.1 est la route par défaut. Non ?

Merci de votre patience

**Comment by marsat** [comment]
je vient  de tester debian 8.5 dans virtual box , et je n'est pas de problème.
même sans modification de scripte.
j'ai encore modifier le scripte pour qu'il soit moins sensible, a des réponses non standard de ip route ou de ifconfig, sa devrai fonctionner maintenant. 
utilise ce deb 
https://github.com/marsat/CTparental/releases/download/4.18.2/ctparental_debian_jessie_4.18.1-2.0_all.deb

**Comment by ersplus** [comment]
Bonjour, 

Impec ! L'installation se passe sans problème ! 

Merci beaucoup

PS : J'ai un autre bug j'ouvre un autre rapport
