### ISSUE TITLE
erreur d'ouverture du fichier /etc/CTparental/categories-enabled.conf

### ISSUE THREAD

**Issue by ersplus** [marsat/CTparental#22]
Bonjour, 
Depuis l'interface web, lorsque l'on modifie la liste blanche et que l'on enregistre, ce message d'erreur apparait :
`erreur d'ouverture du fichier /etc/CTparental/categories-enabled.conf`
En consultant ce fichier, il est vide et les autorisations semblent correctes : 
```
ls -l 
-rw-rw-r-- 1 root www-data 0 juil. 28 09:56 categorie-enabled.conf
```

J'avais déjà eu ce problème sur les précédentes versions. En faisant quelques recherches sur le Net j'ai trouvé un rapport similaire avec alcasar sur Fusion forge.

Lorsque je modifie ce fichier à la main, tout semble fonctionner.

En vous remerciant par avance pour ce projet et le temps que vous y consacrez.

Cordialement

**Comment by marsat** [comment]
l'erreur du a un problème dans le code de l'interface web .
le problème est résolut dans la version de ce lien .
https://github.com/marsat/CTparental/releases/download/4.18.2/ctparental_debian_jessie_4.18.2-1.0_all.deb

**Comment by ersplus** [comment]
Cela fonctionne impec ! merci. Il n'y a plus de message d'erreur et les choix sont conservés !

Merci beaucoup
