### ISSUE TITLE
"iptables host/network 'out;' not found" plus de net

### ISSUE THREAD

**Issue by ersplus** [marsat/CTparental#23]
Un autre petit soucis, 
Suite au démarrage de l'OS je n'ai pas d'internet.  Je lance CTparental -off, internet revient. 
Puis CTparental -on
Un message d'erreur lord du démarrage de CTparental :
<iptablesreload>
"iptables host/network 'out;' not found"

Suite a ceci je lance comme stipulé dans le Wiki 
su nomuser -c "ping youporn.com"
Le résultat est 
unknown host youporn.com

J'ai beau nettoyer et réinstaller idem

Merci d'avance pour vos efforts ;-)

**Comment by marsat** [comment]
lance cette commande et dit mois si le problême persiste.
`CTparental -iptoff`

**Comment by ersplus** [comment]
Idem même message d'erreur et pas de net. Vais essayer une vm pour voir si
je reproduis l'erreur.

Merci 😋

**Comment by ersplus** [comment]
Dans les groupes privilégié l'utilisateur filtré "child" comporte la mention is Admnistrator et je ne peux intervenir dessus. 
Avec la commande CTparental -gctoff

Même erreur iptables
iptables host/network 'out;' not found" 

Hope this help :-)

**Comment by marsat** [comment]
"child" doit faire partie du group **sudo** ou **root**

**Comment by ersplus** [comment]
Pour fonctionner l'utilisateur filtré par le contrôle parental ne doit pas figurer dans le groupe sudo ? Il n'y pas moyen d'y déroger ?

**Comment by ersplus** [comment]
<Mode faineant>
Si je rajoute % devant child ca suffit ou pas ?
il vaut mieux créer un groupe à part C'est ça ?
</Mode faineant>

Pas doué en script...

Je ne sais pas si vous avez ré ouvert pour l'erreur iptables donc je ne ferme pas

Merci en tout cas

**Comment by ersplus** [comment]
Non ça ne marche pas seul le travail paie....

**Comment by marsat** [comment]
si tu veut malgré tous le faire , faut modifier les lignes:
1724 et 1733
`if [ "$(groups "$PCUSER" | grep -c -E "( root$)|( root )")" -eq 1 ];then`

pour l'erreur iptables je comprent pas trops d'ou cela peut venir.
peut tu retourné le retour de commandes suivantes:
`iptables -L -n `
et 
`iptables -L -t nat`

**Comment by marsat** [comment]
`Si je rajoute % devant child ca suffit ou pas ?`
oui cela peut sufir , mais donne acces au répertoir de l'utilisateur de child a tous les utilisateur que tu ajouteras dans le group child.

**Comment by ersplus** [comment]
Ok pas de soucis : 

[iptablesln.txt](https://github.com/marsat/CTparental/files/388496/iptablesln.txt)
[iptablesltnat.txt](https://github.com/marsat/CTparental/files/388495/iptablesltnat.txt)

Vais voir, mais je vais surement créer un groupe.  Lors des mises à jour de ton excellent programme, cela va être trop contraignant.
Merci

**Comment by marsat** [comment]
tes règles iptables sont correcte malgré l'erreur , du coup je comprend pas d’où elle peut venir ??
peut être un bug sous raspberry (debian arm) .
si jamais la conection internet tombe cela peut de dnsmasq ,  
`service dnsmasq status` doit retournet un truque du genre
 ```
dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since jeu. 2016-07-28 14:35:19 CEST; 1h 58min ago
  Process: 22369 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 23214 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 23204 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 23203 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

```

**Comment by ersplus** [comment]
Poissard c'est une état...  Je maitrise...
Voici dnsmasq  status
[dnsmasqstatus.txt](https://github.com/marsat/CTparental/files/388604/dnsmasqstatus.txt)

Merci ;-))

**Comment by ersplus** [comment]
Je clos ce bug. Internet fonctionne avec le groupe sudo.

Merci pour votre patience ;-)
