### ISSUE TITLE
Dépendance php-cgi sur Raspbian

### ISSUE THREAD

**Issue by ersplus** [marsat/CTparental#24]
Bonjour et féliciations pour les évolutions permanentes proposées.

Je viens vers vous pour un problème de dépendance php-cgi lors de la l'installation sur Raspbian. Le paquet php5-cgi est bien disponible dans les dépôts Raspbian, pouvez me dire si l'on peut contourner cette dépendance sans risques pour le fonctionnement de CTparental ?

En vous remerciant pour l'attention portée à ce problème.

Cordialement

**Comment by marsat** [comment]
on peut , mais dans ce cas il faudra ce passer d'interface web d'administration et créer une page d'interception en pur html ou xhtml, cela ne posera donc aucun problème aux fonctionnement de filtrage , mais l'interface de configuration ne fonctionnera plus!
il faudra passer par l'édition manuel des fichier de conf et les commande CTparental

on pourrai même se passer de lighttpd si on de diriger le trafique sur sur une page héberger ailleurs, ou si on ne veut pas d’affichage de page d'interception   , en rajoutent un règle iptables qui refuse explicitement les connexion sur 127.0.0.10:80 et 137.0.0.10:443     .

$IPTABLES -A OUTPUT  -d 127.0.0.10 -p tcp --dport 80 -j REJECT
$IPTABLES -A OUTPUT  -d 127.0.0.10 -p tcp --dport 443 -j REJECT    

sa serai une bonne idée d'évolution pour les machine a faible capacités, sa limiterai un peut les dépendances et la charge.

**Comment by ersplus** [comment]
Merci de votre réponse.

En effet dans l'optique de la borne associative cela serait pas mal en effet de pouvoir héberger l'interface de configuration sur un nas synology par exemple. 

Néanmoins la dernière version de Raspbian pour raspberry a fait un bon en avant spectaculaire en erme de fluidité dans la navigation sur Internet. 

Est ce que le paquet php5-cgi permet de faire fonctionner CT parental ? Car cette borne pourra être mobile.

Encore merci pour le support et le suivi de ce logiciel d'utilité publique  !

Bonne journée

**Comment by marsat** [comment]
> Est ce que le paquet php5-cgi permet de faire fonctionner CT parental ? 

réponse : oui  aucun problème.

**Comment by ersplus** [comment]
Merci de votre réponse.

Pour rebondir, pas seulement pour les machines de faible capacité. Aussi pour les familles nombreuses. Il faudrait qu'un lorsque l'on choisit a l'administration distante, il faudrait que l'administration distante puisse contrôler plusieurs "enfants". Avec une sorte d'association de clients... I have a dream :-))

Merci pour tout, je vais forcer l'installation sur le raspberry pour voir.

Bonne soirée
