### ISSUE TITLE
Erreur de récupération des parametres réseaux 

### ISSUE THREAD

**Issue by mathieuleon** [marsat/CTparental#25]
Bonjour,

J'ai utilisé CTparental en version 4.12.0 pendant un moment sans aucun souci. Hier, j'ai essayé d'installer la version 4.18.3-1.0 sur une Debian Jessie et je rencontre systématique une erreur de récupération des paramètres réseau.
Du coup, j'ai essayé de remettre en place la version 4.12.0 et maintenant je rencontre la même erreur. Ne serait-ce pas lié à une maj d'un packet ?

Si cela peut vous aider (vu sur un autre post), ci-dessous le contenu des commandes "ip route" et "ifconfig"
 
```
ip route
default via 192.168.1.254 dev eth0 
default via 192.168.1.254 dev eth0  proto static  metric 1024 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.34 
```

```
ifconfig
eth0      Link encap:Ethernet  HWaddr 00:19:b9:19:df:fa  
          inet adr:192.168.1.34  Bcast:192.168.1.255  Masque:255.255.255.0
          adr inet6: fe80::219:b9ff:fe19:dffa/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:808632 errors:0 dropped:0 overruns:0 frame:0
          TX packets:397423 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          RX bytes:1192940085 (1.1 GiB)  TX bytes:30288955 (28.8 MiB)
          Interruption:16 
```

```
lo        Link encap:Boucle locale  
          inet adr:127.0.0.1  Masque:255.0.0.0
          adr inet6: ::1/128 Scope:Hôte
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:200 errors:0 dropped:0 overruns:0 frame:0
          TX packets:200 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          RX bytes:58871 (57.4 KiB)  TX bytes:58871 (57.4 KiB)
```

Merci

**Comment by marsat** [comment]
essai  avec cette version : https://github.com/marsat/CTparental/releases/download/4.18.3/ctparental_debian_jessie_4.18.3-2.0_all.deb
elle applique juste un le correctif suivant sur /usr/bin/CTparental 
```
230c230
< ip_route="$(ip route)"
---
> ip_route="$(ip route | tr '\n' ' ')"
```
sa devrai résoudre ton problème.

**Comment by mathieuleon** [comment]
Merci

J'ai essayé cette version et j'ai effectivement réussi à l'installer. J'ai cependant un autre souci avec dansguardian qui ne se lance pas mais je pense que cela n'est pas lié à CTparental. Je vais creuser.
Par contre, si je tape la commande CTparental -on, j'obtiens le mesage "erreur de récupération des paramètres réseaux". Est-ce lié à dansGuardian qui ne marche pas ou est-ce un autre pb ?

**Comment by marsat** [comment]
étant sous sid , je vais installer une jessie , sous virtualbox pour voir d’où cela peut venir.
en attendent peut être réinstallent en suivant ce tuto (lien a modifier en fonction de la version logiciel).

https://github.com/marsat/CTparental/wiki/installation-sous-debian-ubuntu

et si durant la phase d'installation un message pour utiliser le fichier de configuration du paquet ctparental apparaît , bien répondre oui

**Comment by mathieuleon** [comment]
J'avais bien suivi ce guide pour désinstaller et réinstaller CTparental.
Je ferai des tests mais ça sera pour plus tard.

**Comment by marsat** [comment]
bon, je viens de tester en virtualbox install jessie de base , j'ai aucun problème, aurais tu ajouter des depots autre que debian jessie main contrib non-free si oui peut tu me retourner la copy des fichiers suivants:
- /etc/apt/sources.list
- /etc/apt/preferences
- /etc/apt/preferences.d/*

 ainsi que l'architecture utilisée i386 , amd64 ,arm64 ou autre

pour dansguardian qui ne démarre pas je pense que c'est normal vue que ctparental n'a pas pue ce paramétrer, comme il faut .

la configuration dansguardian par defaut fait que le service ne peut pas démarer.
ce problême ce résoudra de lui même quant la détection des paramètre réseaux sera bonne

**Comment by marsat** [comment]
bon d'autre test a partir de tes retour de commande ip route et ifconfig laisse a supposé une mauvaise détection du réseaux box , la version de ce lien corriger ce problème .
https://github.com/marsat/CTparental/releases/download/4.18.3/ctparental_debian_jessie_4.18.3-3.0_all.deb

**Comment by mathieuleon** [comment]
Effectivement, cette version fonctionne parfaitement maintenant. 
Un grand merci à vous pour votre réactivité et le temps passé à résoudre mon problème.
