### ISSUE TITLE
ctparental et ipv6.

### ISSUE THREAD

**Issue by marsat** [marsat/CTparental#29]
l'ipv6 et en court d’intégration , sa évitera de le désactiver , ce qui a long terme n'est pas un bon choix.
- ce qui fonctionne actuellement 
       l’intégration des redirection ip6tables , pour forcer les utilisateurs filtré a utiliser le proxy ( e2guardian + privoxy ).
       les services suivent écoute bien en ipv6 et ipv4 , lighttpd , dnsmasq, privoxy.
- ce qui pose problème.  
      **1**  e2guardian ne tourne pas en ipv6 , tous du moins je n'est pas trouver de documentation sur le sujet, mais le problème semble pris en compte https://github.com/e2guardian/e2guardian/issues/34 .
      **2** n'ayant pas d’accès ipv6 avec mon fournisseur internet, il me manques des retour de commandes pour bien faire, notamment la détection des paramètre ipv6 du réseaux.

ceux qui éventuellement auraient et voudraient aider peuvent poster ici, les retour des commandes suivantes, en précisent la distribution et la version :
       `ip -6 route`
       `ip -6 address`

**Comment by marsat** [comment]
il faut penser a ajouter les proxy suivants pour les utilisateurs filtrés:

proxy http et https : **[::1]**  port **8888**

**Comment by cregouby** [comment]
Bonjour, Sous ubuntu 16.04, nous avons les résultat suivants

ifconfig enx9cebe8341431
enx9cebe8341431 Link encap:Ethernet  HWaddr 9c:eb:e8:34:14:31  
          inet adr:192.168.0.49  Bcast:192.168.0.255  Masque:255.255.255.0
          adr inet6: 2a01:e305:2e08:3020:bdff:d0ff:17ff:81ff/64 Scope:Global
          adr inet6: fe80::73ff:10ff:2eff:24ff/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:37437652 erreurs:0 :41 overruns:0 frame:0
          TX packets:43901529 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          Octets reçus:9269972442 (9.2 GB) Octets transmis:53500787469 (53.5 GB)
⟫ ip -6 route
2a01:e305:2e08:3020::/64 dev enx9cebe8341431  proto ra  metric 100  pref medium
fe80::/64 dev enx9cebe8341431  proto kernel  metric 256  pref medium
fe80::/64 dev wlp2s0  proto kernel  metric 256  pref medium
default via fe80::2a4:d4ff:feff:6aff dev enx9cebe8341431  proto static  metric 100  pref medium

**Comment by marsat** [comment]
Merci pour ton retour **cregouty** j'ai modifier en conséquence en modifient un peut ta ligne pour la rendre moins sensible a des réponse un peut différente de ifconfig .

`ip_i_WAN_ipv6="$(ifconfig "$i_WAN_ipv6" | grep -i global | awk '/inet6[(" "|":")]/{print $3}')"`

**Comment by marsat** [comment]
Microsoft acquiert GitHub! Merci à GitHub , mais je vais sur Gitlab. https://gitlab.com/marsat/CTparental

Microsoft acquires GitHub! Thanks to GitHub, but I'm going on Gitlab. https://gitlab.com/marsat/CTparental
