### ISSUE TITLE
Disfonctionnement et blocage complet

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#30]
Salut,

Comme j'ai déjà dû le dire dans un autre message, j'ai mis en place CTparental sur une dizaine de machine portable pour une école primaire, sous ElementaryOS (encore Freya, donc basée sur Ubuntu 14.04).

C'est pas la première fois que ça arrive, mais (à priori) après une mise à jour automatique de la liste des url de Toulouse, l'accès à internet est impossible sans désactiver CTparental.

À un moment, je pouvais encore régler le problème en forçant une ou plusieurs fois la mise à jour manuellement, mais aujourd'hui non.

Est-ce que la dernière version pour 14.04 pourrait régler ce problème ?

**Comment by marsat** [comment]
Possible je viens de faire une maj de la BL de Toulouse aujourd’hui , pour voir Version actuelle : 21-11-2016 21:42:10 , aucun problème constater , mais je suis sur Debian testing / sid  avec la version  4.20.5_e2guardian.

test ok aussi sous xubuntu 14.04 en virtual box + https://github.com/marsat/CTparental/releases/download/4.20.5d/ctparental_ubuntu14.04_4.20.5-1.0_all.deb

un retour de la commande `sudo netstat -anlp | grep "LISTEN" | grep tcp` donnerai une ide du service qui plante suite a la mise a jour , dnsmasq ou dansguardian, ou les 2 ?

**Comment by cyberesprit** [comment]
Retour de la commande :

```
tcp        0      0 127.0.0.10:80           0.0.0.0:*               LISTEN      1793/lighttpd   
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      1793/lighttpd   
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      1416/dansguardian
tcp        0      0 127.0.0.1:55570         0.0.0.0:*               LISTEN      1580/ica        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      986/sshd        
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2550/cupsd      
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      1442/privoxy    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1793/lighttpd   
tcp        0      0 0.0.0.0:11100           0.0.0.0:*               LISTEN      1580/ica        
tcp        0      0 127.0.0.1:8384          0.0.0.0:*               LISTEN      1662/syncthing  
tcp6       0      0 :::22000                :::*                    LISTEN      1662/syncthing  
tcp6       0      0 :::22                   :::*                    LISTEN      986/sshd        
tcp6       0      0 :::11100                :::*                    LISTEN      1580/ica
```

**Comment by cyberesprit** [comment]
Je viens de mettre à jour avec le dernière version présentée dans un autre ticket, et pour le moment ça fonctionne bien. Donc je vais faire des tests sur plusieurs jours et je reviendrai pour donner un résultat.

**Comment by cyberesprit** [comment]
Salut, Je suis toujours sur le coup, j'attends un peu vu que c'est tout récent.

**Comment by cyberesprit** [comment]
bon je confirme que pour le moment en tout cas tout est fonctionnel ;-)
Je cloture, merci beaucoup !
