### ISSUE TITLE
Non conservation du status on/off au redémarrage

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#31]
Salut,

J'ai remarqué que si on désactivait CTparental, au redémarrage de l'ordinateur il était tout de même démarré (alors que l'on pourrait attendre qu'il ne démarre pas jusqu'au prochain démarrage manuel).

Qu'en penses-tu ?

**Comment by marsat** [comment]
oui tu a raison, CTparental ne devrai pas ce réactiver aprés un redémarage je regarde sa de plus prés dans ma vbox xubuntu 14.04

**Comment by marsat** [comment]
cela semble du a la non suppression de taches dans cron, correctif en cour. 
voir https://github.com/marsat/CTparental/commit/acedef84d0ed5ed47832b043f2f069062d2a9869

**Comment by marsat** [comment]
problème résolut dans cette version https://github.com/marsat/CTparental/releases/download/4.20.6d/ctparental_ubuntu_14.04_4.20.6-1.0_all.deb

**Comment by cyberesprit** [comment]
Super merci, je vais tester ça rapidement ;-)

**Comment by cyberesprit** [comment]
J'ai testé, ça fonctionne ! Par contre si CTparental est désactivé, plus aucun accès internet n'est possible (du moins via un navigateur web). Hors ça devrait laisser tout passer au contraire, non ?

**Comment by marsat** [comment]
problème lier a resolvconf et aux paramétrage automatique du proxy , résolut dans cette version:

https://github.com/marsat/CTparental/releases/download/4.20.7d/ctparental_ubuntu_14.04_4.20.7-1.0_all.deb

**Comment by cyberesprit** [comment]
Testé et approuvé ;-)
Merci beaucoup !
