### ISSUE TITLE
Contact direct pour question de curiosité et de compréhension

### ISSUE THREAD

**Issue by cyberesprit** [marsat/CTparental#32]
Salut,

Est-il possible qu'on se mette en contact direct (courriel, tox, irc, ...) pour des questions d'ordre technique par exemple.

Je me demandais justement pourquoi mettre clamav avec CTparental, quel est son utilité ?

**Comment by marsat** [comment]
oui pas de problème on peut me joindre ici. CTparental1_arobase_laposte.net
