### ISSUE TITLE
Problème d'installation CTParental

### ISSUE THREAD

**Issue by Owl-Express** [marsat/CTparental#33]
Voici le problème : ctparental_ubuntu_16.04_4.20.7-1.0_all.deb

sudo gdebi ctparental_*_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Controle parental.
 Filtrage web basé sur dnsmasq, lighttpd et cron,
 une gestion des horaires de connection est aussi intégrée et
 une interface web (http://127.0.0.1/CTadmin) permettant de paramétrer tous ça.
 Le couple login mot de passe doit être saisi à l'install, mais peut être
 modifié par la suite grâce à la commande CTparental.sh -uhtml.
Do you want to install the software package? [y/N]:y
(Reading database ... 418819 files and directories currently installed.)
Preparing to unpack ctparental_ubuntu_16.04_4.20.7-1.0_all.deb ...
<dnsmasqoff>
<resolvconffixon>
Job for dnsmasq.service failed because the control process exited with error code. See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
</resolvconffixon>
</dnsmasqoff>
<resolvconffixoff>
</resolvconffixoff>
<iptablesreload>
<unsetproxy>
<unsetproxy/>
 * Saving netfilter rules...                                                                                                                                                                          run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
                                                                                                                                                                                               [ OK ]
</iptablesreload>
<unsetproxy>
<unsetproxy/>
 * Saving netfilter rules...                                                                                                                                                                          run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
                                                                                                                                                                                               [ OK ]
Unpacking ctparental (4.20.7-1.0) over (4.20.7-1.0) ...
Setting up ctparental (4.20.7-1.0) ...
<iptablesreload>
<unsetproxy>
<unsetproxy/>
 * Saving netfilter rules...                                                                                                                                                                          run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
                                                                                                                                                                                               [ OK ]
</iptablesreload>
Waiting to Connect to Server from Toulouse:.......................................The connection to the server of Toulouse is impossible.dpkg: error processing package ctparental (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 ctparental

**Comment by marsat** [comment]
ctparental a besoins d'internet pour s'installer correctement il semblerai que durant l'installation il lui a était impossible de télécharger la blacklist sur le serveur de l'université de toulouse.

essai ceci:
`sudo apt-get autoremove --purge dnsmasq privoxy dansguardian clamav*`

redémarre l'ordinateur est vérifie si que tu est bien accès a internet.

si oui refait une tentative d'install
`
sudo gdebi ctparental_ubuntu_16.04_4.20.7-1.0_all.deb`

**Comment by marsat** [comment]
doublon avec post https://www.debian-fr.org/t/bug-ctparental-sh/60671/54

résolut dans post https://www.debian-fr.org/t/bug-ctparental-sh/60671/75
