### ISSUE TITLE
Débloquer Skype

### ISSUE THREAD

**Issue by Cyrixo** [marsat/CTparental#34]
Bonjour,

Je cherche à débloquer skype.
J'ai autorisé plusieurs domaines : live.fr outlook.fr microsoft.fr skype.fr mais rien n'y fait.
Pourriez-vous m'indiquer une méthode ?
Pour infos, ctparental est installé sur Mint 18.
Merci d'avance.

**Comment by marsat** [comment]
c'est étrange , j'ai aucun problème a me connecter a skype avec CTparental , aurai tu par asar activer la gestion du par feux , pour verifier que sa ne vient pas de la essai  déjà ceci 

`sudo CTparental -iptoff`

pour la version ctparental mint 18 je pense que celle de ce liens est a préférer . 
https://github.com/marsat/CTparental/releases/download/4.20.9d/ctparental_ubuntu16.04_4.20.9-1.0_all.deb

**Comment by marsat** [comment]
et pour être sur que c'est bien CTparental qui bloque skype désactive le complètement avec la commande 
`sudo CTparental -off	`
fait un teste de connexion , si sa marche toujours pas le problème vient d’ailleurs . si sa fonctionne c'est que c'est bien CTparental qui te bloque.

**Comment by Cyrixo** [comment]
J'ai bien installé la version pour ubuntu 16.04.
Pour info, depuis le compte administrateur, skype se connecte sans problème, c'est depuis le compte des enfants qu'il ne fonctionne pas.
Si je désactive le filtrage web, alors skype se connecte sans problème ( depuis compte enfant ), c'est donc bien le filtrage web qui bloque.

**Comment by marsat** [comment]
quel version de skype a tu installer ?
peut ètre que la détection du proxy automatique ne marche pas ou mal .
essai d’ajouter le proxy https suivant 127.0.0.1 port 8080
sans aucun identifiant mot de passe.
clic droit sur l'icone skype qui apparer dans le tableau de bord puis options => avancé
c'est la que ce trouve le paramètre proxy skype.

**Comment by Cyrixo** [comment]
De mémoire, c'est skype 4.3.
Je teste ta solution en début de soirée et je te redis.
Merci

**Comment by Cyrixo** [comment]
Bon j'ai eu le temps de tester.
Et effectivement c'est bien le proxy qui n'est pas détecté.
En configurant le proxy https depuis skype, ça fonctionne correctement.
Je te remercie pour la solution et aussi pour CTparental.
Bonne continuation.

**Comment by marsat** [comment]
merci a toi pour ton retour il servira a d'autres :)

**Comment by Cyrixo** [comment]
Bonjour,

J'ai crié victoire trop vite....

Depuis la fenêtre de connexion de Skype, on peut choisir de se connecter de deux façons.

1 - soit depuis pseudo et son mot de passe. Et là ça fonctionne bien.Proxy skype modifié ou pas.

2 - soit en choisissant le " Compte Microsoft ". Et là pas de connexion. Proxy skype modifié ou pas.
On a le droit a une roue qui tourne une bonne dizaine de fois et on finit par tomber sur un message qui nous dit : " Internet est parfois très lent. Vérifier que votre connexion fonctionne correctement.

Aurais-tu une idée du pourquoi comment.
Je peux fournir le retour de commade, si il le faut.
Merci d'avance.

**Comment by marsat** [comment]
j'ai pas de compte microsoft je me connecte toujours par pseudo/mot de passe

je viens de tester  " Compte Microsoft " juste pour voir , mais j'ai aussi le même problème que toi sans CTparental installer sa vient donc de skype.
je pense qu'il doit falloir renseigner les infos du compte quelque par dans skype, mes la je vois pas ou ??

**Comment by Cyrixo** [comment]
Euh, chez moi, si je désactive le filtrage web pour la session des enfants, je peux utiliser le " Compte Microsoft ". Si le filtrage est activé je ne peux pas.
Je pense donc que c'est bien CTparental qui bloque le " Compte Microsoft ".

N'y a-t-il pas moyen de voir quelles sont les requêtes qui sont bloquées lors de la tentative de connexion avec le " Compte Microsoft " ?
Si oui, ne serait-il pas possible d'ajouter les domaines ou IP en whitelist

**Comment by marsat** [comment]
pour voir les requêtes dns qui sont faite.
active les log query de dnsmasq en lancent cette commande.
sudo CTparental -logqueryon

fait une tentative de connection sqype
les logue de requet ce trouve dans /var/log/dnsmasq.query.log
pour les voir en live 
sudo tail -f /var/log/dnsmasq.query.log
ce qui est bloque et redirigé ver 127.0.0.10

**Comment by Cyrixo** [comment]
Lignes du ` /var/log/dnsmasq.query.log ` contenant 127.0.0.1 lors de la tentative de connexion depuis " Compte Microsoft "

`Feb  8 20:53:36 dnsmasq[10689]: query[A] b.config.skype.com from 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: forwarded b.config.skype.com to 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: query[AAAA] b.config.skype.com from 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: forwarded b.config.skype.com to 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: query[A] a.config.skype.com from 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: query[AAAA] a.config.skype.com from 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: query[A] apps.skypeassets.com from 127.0.0.1`
`Feb  8 20:53:36 dnsmasq[10689]: query[AAAA] apps.skypeassets.com from 127.0.0.1`
`Feb  8 20:53:47 dnsmasq[10689]: query[A] login.live.com from 127.0.0.1`
`Feb  8 20:53:47 dnsmasq[10689]: query[AAAA] login.live.com from 127.0.0.1`

J'ai donc ajouté les domaines skype.com, skypeassets.com et live.com aux domaines réhabilités et enregistrer. Cela ne fonctionne toujours pas.

Ce qui m'étonne un peu c'est que je retrouve les mêmes lignes dans le log après avoir ajouté ces domaines.

J'ai loupé un truc ?

**Comment by marsat** [comment]
query[A] c'est dnsmasq qui resoi une demande de résolution de nom
forwarded c'est dnsmasq qui devrai interoger ton dns fai pour conètre la réponse mais la il interoge 127.0.0.1 ce qui est etrange.
vas voirdans /etc/dnsmasq.conf si tu a bien les ip des dns FAI en face des lignes commenssent par:
server=
si tu conner pas les dns de ton fai mais
server=8.8.8.8
c'est le dns google.

**Comment by marsat** [comment]
petite remarque quant tu a déterminer ce qui clocher désactive les log query avec la commande 
sudo CTparental -logqueryoff
car cela créer des fichier très volumineux a la longue.

**Comment by Cyrixo** [comment]
On avance, effectivement j'avais une ligne dans le ` /etc/dnsmasq.conf ` qui contenait ` server=127.0.0.1 `
J'ai mis l'IP du dns de mon FAI à la place.

Donc il n'y a plus de forwarded vers 127.0.0.1 dans les log, c'est déjà ça de gagner.
Par contre on ne peut toujours pas se connecter à skype par le " Compte Microsoft ".

Voici le log complet : http://pastebin.com/CPyGYwtF
Peut-être y verras tu des erreurs.

**Comment by marsat** [comment]
au vue des logs ce n'est pas dnsmasq qui bloque . car il ne retourne jamais la page de redirection 127.0.0.10 . 
le problême vient donc peut être de privoxy ou de dansguardian bien que je ne pense pas vue que ces 2 la ne filtre pas tous e qui est connexion https, mais dans le doute essai de désactiver Le filtrage par défaut de privoxy via l'interface, si sa marche toujour pas décoche toutes les extensions a filtrées ainssi que les type MIME a filtrer.

**Comment by Cyrixo** [comment]
> dans le doute essai de désactiver Le filtrage par défaut de privoxy via l'interface

Pas compris comment désactiver privoxy via l'interface ??

**Comment by marsat** [comment]
dans le **Filtrage par BlackList** juste en dessous **La mise à jour de la blacklist de Toulouse tous les 7 jours** tu a  **Le filtrage par défaut de privoxy est activé.** clique dur **Désactiver** , sa désactive pas privoxy , mais sa désactive les règles de filtrages par defaulf de celui-ci.

**Comment by Cyrixo** [comment]
Désolé j'avais de la me_de dans les yeux.........
J'ai donc, désactiver privoxy, décocher les extensions a filtrées et les type MIME.

On ne peut toujours pas se connecter à skype par le " Compte Microsoft ".
Par contre si je désactive le filtrage web nom de domaine, là ça marche.

**Comment by marsat** [comment]
il doit y avoir  un problème de compatibilité avec privoxy , ou dansguardian, je vais essayer de reproduire le problème cher moi en virtual box, la je voie pas trop d’où cela peut venir désoler .

**Comment by Cyrixo** [comment]
En tout cas merci d'avoir cherché.

Une dernière question, pourrait-il y avoir un rapport avec iptable ?

**Comment by marsat** [comment]
iptable, seulement si tu a jouter des règles de filtrage , par default CTparental ne les active pas.

autre piste esai avec la toutes dernière version de skype pour linux:

https://www.skype.com/en/download-skype/skype-for-linux/downloading-web/?type=weblinux-deb

**Comment by Cyrixo** [comment]
Je n'ai pas touché à iptable.
Le skypeforlinux ne fonctionne pas correctement ( fenêtre blanche avec un gros carrée noir au milieu )
