### ISSUE TITLE
Erreur 404 pour accéder à la console d'administration

### ISSUE THREAD

**Issue by ForumCTparentalLaurent** [marsat/CTparental#36]
Bonjour,
Je débute sur Ubuntu. J'ai Ubuntu 17.04, je l'ai installé très récemment, donc il y a eu peu de modif depuis.

J'ai installé CTparental (v-4.20.17-1.0 pour ubuntu 16.04 , depuis le lien dispo sur la page https://doc.ubuntu-fr.org/tutoriel/comment_mettre_en_place_un_controle_parental) , tout semble s'être bien passé. 
Mais ensuite impossible d'accéder à la console d'administration, quand j'essaie d'aller à http://127.0.0.1/CTadmin j'ai un message d'erreur (404 - Not Found).

Pourriez-vous m'aider svp ?
Merci beaucoup
Laurent

**Comment by ForumCTparentalLaurent** [comment]
J'ai essaye une manip en suivant le tuto de Ubuntu, j'ai exécuté dans le terminal la commande "sudo CTparental", et dans ce qui s'afiche ensuite il semble qu'il y ait un problème (ifconfig : commande introuvable):

/usr/bin/CTparental: ligne 264: ifconfig : commande introuvable
/usr/bin/CTparental: ligne 269: ifconfig : commande introuvable
/usr/bin/CTparental: ligne 275: ifconfig : commande introuvable
/usr/bin/CTparental: ligne 276: ifconfig : commande introuvable
/usr/bin/CTparental: ligne 307: ifconfig : commande introuvable
Argument inconnu:
Usage: CTparental    {-i }|{ -u }|{ -dl }|{ -ubl }|{ -rl }|{ -on }|{ -off }|{ -cble }|{ -dble }
                               |{ -tlo }|{ -tlu }|{ -uhtml }|{ -aupon }|{ -aupoff }|{ -aup } 
-i	=> Installe le contrôle parental sur l'ordinateur (pc de bureau). Peut être utilisé avec
	    un paramètre supplémentaire pour indiquer un chemin de sources pour la page web de redirection.
	    exemple : CTparental -i -dirhtml /home/toto/html/
	    si pas d'option la page par défaut est utilisée.
-u	=> désinstalle le contrôle parental de l'ordinateur (pc de bureau)
-dl	=> met à jour le contrôle parental à partir de la blackliste de l'université de Toulouse
-ubl	=> A faire après chaque modification du fichier /etc/CTparental/blacklist-local.conf
-rl	=> A faire après chaque modification du fichier /etc/CTparental/domaine-rehabiliter.conf 
-on	=> Activer le contrôle parental
-off	=> Désactiver le contrôle parental
-cble	=> Configure le mode de filtrage par liste blanche ou par liste noire (défaut)
	   ainsi que les catégories que l'on veut activer.
-dble	=> Remet les catégories actives par défaut et le filtrage par blackliste.
-tlo	=> Active et paramètre les restrictions horaires de login pour les utilisateurs.
-tlu	=> Désactive les restrictions horaires de login pour les utilisateurs.
-uhtml	=> met à jour la page de redirection à partir d'un répertoire source ou par défaut.
	   exemples:
	           - avec un répertoire source : CTparental -uhtml -dirhtml /home/toto/html/
	           - par défaut : CTparental -uhtml
	   permet aussi de changer le couple identifiant,mot de passe de l'interface web.
-aupon	=> active la mise à jour automatique de la blacklist de Toulouse (tous les 7 jours).
-aupoff	=> désactive la mise à jour automatique de la blacklist de Toulouse.
-aup	=> comme -dl mais seulement si il n'y a pas eu de mise à jour depuis plus de 7 jours.
-nodep	=> si placé aprés -i ou -u permet de ne pas installer/désinstaller les dépendances, utiles si
	   on préfère les installer à la main , ou pour le script de postinst et prerm du deb.
	   exemples:
	           CTparental -i -nodep
	           CTparental -i -dirhtml /home/toto/html/ -nodep
	           CTparental -u -nodep
-nomanuel	=> utilisé uniquement pour les scripts de postinst et prerm.
-gcton	=> crée un groupe de privilégiés ne subissant pas le filtrage.
	   exemples:
	           CTparental -gctulist
	           commenter tous les utilisateurs que l'on veut filtrer dans /etc/CTparental/GCToff.conf
	           CTparental -gctalist
-gctoff	=> supprime le groupe de privilégiés .
	   tous les utilisateurs du système subissent le filtrages!!
-gctalist	=> Ajoute/Supprime les utilisateurs dans le group ctoff en fonction du fichier de configuration, /etc/CTparental/GCToff.conf 
-ipton	=> Active les règles de pare-feu personnalisées.
-iptoff	=> Désactive les règles de pare-feu personnalisées.
-grubPon	=> Activer l'administrateur de grub2.
-grubPoff	=> Désactiver l'administrateur de grub2.
-pfoff	=> Désactiver les règles privoxy par défaut.
-pfon	=> Activer les règles par défaut de privoxy.
-ron	=> Enable rectidect page.
-roff	=> Disable rectidect page.

Est-ce que ça donne des idées à quelqu'un pour que je m'en sorte ?Bonne soirée
Laurent

**Comment by marsat** [comment]
c'est tous de même étrange qu'il ne trouve pas la commande ifconfig avec sudo .
c'est bien avec le compte qui administre le poste que tu a lancer cette commande ??

je vais installation  ubuntu 17.04  dans un Virtualbox pour voir ce qui ce passe de mon coté.

**Comment by ForumCTparentalLaurent** [comment]
Oui oui, c'est bien avec le compte principal que j'essaie d'accéder à CTparental.

Merci de ton aide en tous cas.

**Comment by marsat** [comment]
bon a parement sous ubuntu 17.04 `ifconfig` n'est pas installé par défaut , voici ce que je te conseille:

- en premier désinstalle ctparental `sudo apt-get autoremove ctparental dnsmasq privoxy dansguardian`
- installer gdebi-core `sudo apt-get install gdebi-core`
- télécharger la version pour ubuntu 17.04 `wget -c https://github.com/marsat/CTparental/releases/download/4.20.19e/ctparental_testing_sid_ubuntu17.04_4.20.19-1.0_all.deb`
- puis l'installer avec la méthode gdebi , `sudo  gdebi ctparental_testing_sid_ubuntu17.04_4.20.19-1.0_all.deb`
sa a marcher pour moi dans virtualbox , tiens mois au courant si c'est bon pour toi.

**Comment by ForumCTparentalLaurent** [comment]
Salut marsat,
Merci beaucoup ça a parfaitement fonctionné!

Maintenant j'ai un autre problème, c'est de bien configurer la plateforme d'administration, puisque là pour l'instant l'accès aux sites 'adultes' est toujours possible depuis le compte de mon fils. Mais je devrais m'en débrouiller en cherchant un peu.

Merci encore de ton aide!
Bonne journée
Laurent

**Comment by marsat** [comment]
bon j'ai trouver le problème cela viens de service de résolution de nom installer par défaut dans ubuntu qui semble prendre le dessus sur tous même le forsage du dns par les iptables.

pour le désactiver ajoute ces 2 ligne a la fin du fichier
/etc/CTparental/dist.conf

```
systemctl stop systemd-resolved
systemctl disable systemd-resolved
```
puis lance la commande `sudo CTparental`
sa résoudra les problême.

**Comment by marsat** [comment]
bon je suit en trains de revoir mon scripte en ce qui conserve la détections des infos du réseaux de manière a ne plus utiliser des commande obsolète comme `ifconfig` remplacer par `ip addr` ...
cela supprime la dépendance a net-tools , mais risque de casé la rétros compatibilité. faut aussi que je creuse pour voir ce problème avec systemd-resoved , voir si il y a pas moyen d'éviter sa désactivation total.

**Comment by ForumCTparentalLaurent** [comment]
Salut,
Merci pour tes deux derniers messages. Si je comprends bien le dernier, il vaut mieux que je n'applique pas pour l'instant ta solution du message d'avant (les 2 lignes à ajouter dans dist.conf). C'est ça ?

Bonne journée
Laurent

**Comment by marsat** [comment]
systemd-resoved semble pauser pas mal de problème sous ubuntu 17.04 , mais je comprend pas encore bien comment fonctionne le bousin car les règles iptables devrais rediriger tous le trafique dns des utilisateurs filtré et de privoxy vers dnsmasq (dns + blaqueliste de toulouse), mais bien qu'elles soit présentes elle ne semble pas s'appliquer. 

pour tester j'ai activer systemd-resoved sous ma debian sid , sa ma bien ajouter le serveur en 127.0.0.53 mais sans me supprimer ceux qui exister déjà et ctparental semble encore fonctionner, bref peut être que les problème serons résolus a la prochaine LTS  .

et effectivement évite d'appliquer la solution précédente sa fonctionne que partiellement  .

**Comment by ForumCTparentalLaurent** [comment]
Merci,
et si j'installais Ubuntu 16.04 au lieu de 17.04, peut-être que j'aurais moins de soucis?

Mon installation étant toute récente, je pourrait effacer tous mes fichiers sans que ça pose problème...

Bonne journée
Laurent

**Comment by ForumCTparentalLaurent** [comment]
Sinon encore une autre solution: désinstaller CTparental pour Ubuntu 16.04, et installer à la place la version pour Ubuntu 17.04 (depuis peu il y a un lien vers cette version depuis la page: https://doc.ubuntu-fr.org/tutoriel/comment_mettre_en_place_un_controle_parental

Si la version est plus adaptée, il n'y aura peut-être plus de bug ?

**Comment by marsat** [comment]
> et si j'installais Ubuntu 16.04 au lieu de 17.04, peut-être que j'aurais moins de soucis?

oui il n'y a pas ces problème la sous ubuntu 16.04 car systemd-resolved n'a étais utiliser par default qu'a partir de ubuntu 17.04. 

> depuis peu il y a un lien vers cette version depuis la page:

oui j'avais mi a jour la doc ubuntu un peux rapidement , le paquet en question et le même que fourni plus haut.

je laisse ce file ouvert jusqu’à ce que je trouve une solution suffisamment stable.

**Comment by marsat** [comment]
bon voici un nouveaux paquet qui devrais résoudre le problème ne tous cas sa a fonctionner dans ma virtual box 

https://github.com/marsat/CTparental/releases/download/4.20.20e/ctparental_testing_sid_ubuntu17.04_4.20.20-1.0_all.deb

**Comment by ForumCTparentalLaurent** [comment]
Super , merci beaucoup, j'essaie ça ce week-end!
Bonne soirée
Laurent

**Comment by ForumCTparentalLaurent** [comment]
Bonjour,
Désolé d'avoir été si long à donner des nouvelles... Finalement j'ai installé Ubuntu 16.04, et CTparental fonctionne à merveille dessus, c'est vraiment génial. Merci beaucoup!
Laurent

**Comment by marsat** [comment]
problem avec ubuntu17.04 resolute dans la v 4.20.22 .
