### ISSUE TITLE
Traducción al español

### ISSUE THREAD

**Issue by nachosalgado** [marsat/CTparental#42]
Hola.

Espero que mi aportación pueda resultaros útil.

Gracias por vuestra confianza.

Un saludo

Nacho Salgado

[CTparental-ES.zip](https://github.com/marsat/CTparental/files/1533120/CTparental-ES.zip)

**Comment by marsat** [comment]
Hola.
muchas gracias por su contribución, tengo la integración en la nueva versión de ctparental que tendrá que irse antes de Navidad .

**Comment by nachosalgado** [comment]
Ha sido un placer. Estupendo. Gracias.

Saludos



2017-12-06 10:45 GMT+01:00 marsat <notifications@github.com>:

**Comment by marsat** [comment]
aquí está integrado, podemos probar a través de Deb Pre-lanzamiento 4.20.26 ***
Salgo en Prelanzamiento durante el tiempo que aún no he probado en diferentes sistemas, solo en Debian testing / sid.
https://github.com/marsat/CTparental/releases
Prelanzamiento 4.20.26 e2guardian para debian 9 y up y ubuntu 17.04 y posteriores
Prelanzamiento 4.20.26 inguardian para debian 8 y ubuntu 16.04
