### ISSUE TITLE
Information utilisateur

### ISSUE THREAD

**Issue by nikrou** [marsat/CTparental#43]
Bonjour,
j'ai installé CTparental sur le PC familial utilisé par mes enfants via le package debian. Cela fonctionne très bien.
J'ai modifié à la main le fichier de conf de lighttpd pour pouvoir administrer la bête à distance.
J'ai mis des filtres de temps pour mes enfants. Ils voient bien la durée mais ils ne comprennent pas pourquoi ils ne peuvent plus se connecter et sans avoir besoin d'aller jeter un oeil dans  /etc/CTparental/CThourscompteur j'aimerais voir depuis l'interface d'admin une information de ce type.
Si cela existe déjà je n'ai pas trouvé.

**Comment by marsat** [comment]
c'est effectivement une bonne idée de pouvoir afficher la consommations du temps  journalier de navigation , ce serra pas pour tous de suite mais je garde l'idée dans un coins.

**Comment by nikrou** [comment]
Et si je fais une pull request ça peut aider ? :-)

**Comment by marsat** [comment]
bien effectivement si tu à le temps et les compétences pour faire la/les modifications , et les proposée via pull request , cela accéléreras l'ajout de la fonctionnalité, toutes participations étant la bien venus.

**Comment by marsat** [comment]
l'ajout du temps de connexion et de navigation déjà utilisé dans l'interface administration seras présent dans la prochaine version.
![capture d ecran_2018-01-20_13-48-32](https://user-images.githubusercontent.com/6809414/35183576-d751d158-fde8-11e7-8f9f-18f9cd9217a2.png)
