### ISSUE TITLE
crontab trop verbeuse?

### ISSUE THREAD

**Issue by christophe-lyon** [marsat/CTparental#44]
Bonjour,
Je trouve que la crontab est trop verbeuse, car toutes les minutes je recois un mail avec la sortie de certaines commandes utilisees par CTparental:
PING 192.168.0.254 (192.168.0.254) 56(84) bytes of data.
64 bytes from 192.168.0.254: icmp_seq=1 ttl=64 time=2.01 ms

--- 192.168.0.254 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.013/2.013/2.013/0.000 ms
<dnsmasqon>
<resolvconffixon>
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
</resolvconffixon>
</dnsmasqon>
<iptablesreload>
 * Saving netfilter rules...
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
   ...done.
<updatecauser>
</updatecauser>
</iptablesreload>
PING 192.168.0.254 (192.168.0.254) 56(84) bytes of data.
64 bytes from 192.168.0.254: icmp_seq=1 ttl=64 time=2.50 ms

--- 192.168.0.254 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.508/2.508/2.508/0.000 ms
<updatecauser>
</updatecauser>

Est-il possible de supprimer ces messages ou les gardez-vous pour une bonne raison?

Par ailleurs j'ai observe que le script met environ 15 secondes a s'executer. Comme il est appele toutes les minutes, n'est-ce pas un peu trop?

Merci,

C.Lyon

**Comment by marsat** [comment]
non pas de raisons  je vais voir, pour suprimer les retours des commande dans crontab , pour le mail je suppose que vous avais rajouter quelque chause car ctparental ne fais pas de remonter mail des infos log crontab.

**Comment by marsat** [comment]
pour ampécher des retour dans cron edit ce fichier /etc/cron.d/CTparentalcron
et replace la ligne par celle ci:

`*/1 * * * * root /usr/bin/CTparental -cron > /dev/null 2&>1`

**Comment by marsat** [comment]
non c'est pas grave 15 secondes ou 30 secondes, temps que l'on ne dépasse pas la minutes :) la sa poserais un problème, tu remarqueras que même si c'est un peut long ,la charge prose + ram et négligeable.
chez moi 3 seconde seulement , dont 2 incompressible car du aux 2 test ping ipv4 et ipv6 1seconde par test, le reste pédant principalement du nombres de comptes utilisateurs a traiter sur le postes, et de la vitesse du disque dur.

**Comment by marsat** [comment]
la version 4.20.29 rend crontab moins verbeuse .

**Comment by marsat** [comment]
>Par ailleurs j'ai observe que le script met environ 15 secondes a s’exécuter. Comme il est appelé toutes les minutes, n'est-ce pas un peu trop?

la version 4.21.05 apporte une nette amélioration de ce coté la  , surtout si les profile de vos utilisateur sont volumineux ou avec un grand nombres de fichiers.
