### ISSUE TITLE
installation sur raspberry PI 3B

### ISSUE THREAD

**Issue by loick2000** [marsat/CTparental#45]
Bonjour, 

J'ai trouvé le lien sur le forum franboise314 dans le fil de discutions "Installer CTparental"

Je suis informaticien (unix mais pas ingé système). il me semble que la nouvelle version n'est plus sous jessie
Est-ce que vous avez eu des retour d'utilisation sur une raspbian stretch ?

J'ai bien envie d'installer le  ctparental_debian9_4.20.28-1.0_all.deb, mais je voulais savoir si quelqu'un l'avais déjà testé.

Cordialement,
Loïc

**Comment by marsat** [comment]
si CTparental et sous jessie (debian 8) aussi 
https://github.com/marsat/CTparental/releases/download/4.20.28d/ctparental_debian8_4.20.28-1.0_all.deb

pour ce qui est du retour sur raspberry PI je n'est et malheureusement pas. je n'est pas pus tester.

**Comment by loick2000** [comment]
Je vais essayé de tester ce WE.
Je te tiens au courant de mes résultats.

**Comment by marsat** [comment]
la https://github.com/marsat/CTparental/releases/download/4.20.29d/ctparental_debian8_4.20.29-1.0_all.deb ,correction d'un bug dans le gestion du temps de connexion qui n'était pas prit en compte. et rend les crontab moins verbeuse.

**Comment by loick2000** [comment]
le .deb ne s'installe pas, il me dit qu'il lui manque un paquet pour s'installer, et ne me dit pas lequel. Et comme je débute sur gadget, je ne sais meme pas ou chercher le log qui contient le nom du paquet manquant.

**Comment by marsat** [comment]
bon je pense que tu a du faire un dpkg -i ctparental....deb , mais cette comande n'installee pas les dépendence. tente ceci:

avec une conection internet valide , 
`apt-get install gdebi-core`
`wget https://github.com/marsat/CTparental/releases/download/4.21.00d/ctparental_debian8_4.21.00-1.0_all.deb`
`gedbi ctparental_debian8_4.21.00-1.0_all.deb`

**Comment by loick2000** [comment]
Mince, j'ai eu le message trop tard. J'ai fait le paquet pour mes neveux, je pars ce matin pour leur amener.

J'espère que ces messages aideront un autre internaute. Si je rachète une machine pour chez moi,  je ferai le test.

Merci pour tes réponses rapides.
