### ISSUE TITLE
Indentation?

### ISSUE THREAD

**Issue by christophe-lyon** [marsat/CTparental#46]
Bonjour, je pensais eventuellement contribuer quelques ameliorations, corrections d'orthographe etc...
et j'ai une premiere question: avez-vous une convention d'indentation du script?
Il me semble que je vois un melange de tabs et d'espaces, du coup si je re-indente, il risque d'y avoir des conflits inutiles... Est-ce qu'un 1er commit qui reindente le code est acceptable?
Chez moi, emacs indente par 4 espaces, puis 1 tab. Est-ce OK pour vous?

**Comment by marsat** [comment]
Bonjour,
> avez-vous une convention d'indentation du script?
non j'utilise le plus souvent la tabulation mais rien de carré dans tous sa, comme je le dit souvent, toutes contribution et la bien venus et sa rendrai le code plus lisible , donc oui aucun problème pour le(s) commit(s) , n’étant pas un professionnel du codage je n'est pas d'avis trancher sur le choix de l'indentation donc vas pour 4 espaces, puis 1 tab.
et merci pour ta proposition d'amélioration.
