### ISSUE TITLE
Problemes de certificats

### ISSUE THREAD

**Issue by christophe-lyon** [marsat/CTparental#48]
Bonjour,
Sur Ubuntu 17.10, j'ai des problemes avec les certificats de ctparental, qui sont refuses par Chromium ET par firefox. Du coup, les utilisateurs filtres ne peuvent pas utiliser internet du tout :)

**Comment by marsat** [comment]
essai avec cette commande voir si sa résout ton problème.
`sudo CTparental -cainstall`

**Comment by christophe-lyon** [comment]
Non cela ne change rien.
Pour info, firefox dit:
Le certificat n'est valide que pour les nms suivants:
admin.ct.loca, privet.ct.local
Code d'erreur: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by ChMaille** [comment]
Bonjour
J'ai également un problème de certificat sous Ubuntu 17.10 Firefox 58.0.1 (64 bits).

"La connexion n’est pas sécurisée
Les propriétaires de admin.ct.local ont mal configuré leur site web. Pour éviter que vos données ne soient dérobées, Firefox ne s’est pas connecté à ce site web.

admin.ct.local utilise un certificat de sécurité invalide.
Le certificat a expiré le 4 février 2018 à 07:13. La date courante est 7 février 2018 à 14:27.
Code d’erreur : SEC_ERROR_EXPIRED_CERTIFICATE "

Je suis obligé d'ajouter une exception pour pouvoir continuer.

**Comment by marsat** [comment]
un bug  sur la génération des certificats fait que ceux si expire un moi après ce qui peut causée ce problème résolut dans la version 4.21.01
https://github.com/marsat/CTparental/releases/tag/4.21.01e
https://github.com/marsat/CTparental/releases/tag/4.21.01d

**Comment by marsat** [comment]
tu peux aussi résoudre le problème temporairement avec la commande 
sudo CTparental -uhtml

**Comment by marsat** [comment]
pour ubuntu 17.10 il faut installer ifupdown2 ou ifupdown avant ctparental
`sudo apt-get install  ifupdown2`

**Comment by ChMaille** [comment]
Fonctionne à présent avec la version 4.21.01
Merci !
