### ISSUE TITLE
Langue Française non prise en compte

### ISSUE THREAD

**Issue by ChMaille** [marsat/CTparental#49]
Bonjour
Le wiki précise que :

> la langue peut être forcée, en ajoutant ou modifiant le paramètre LANG=fr_FR.utf8 dans /etc/CTparental/CTparental.conf.

C'est bien le cas de mon fichier et cependant, l'interface web est toujours en Anglais.
Pouvez-vous m'aider svp ?

**Comment by marsat** [comment]
test avec la verssion 4.21.01

**Comment by ChMaille** [comment]
Teste la version la version 4.21.01. (désinstallation de la version précédente et redémarrage du PC)

- Interface web en Français sous Xubuntu 17.10 
- Interface web en Anglais sous Ubuntu 17.10 (même en ayant décommenté la ligne "LANG=fr_FR.utf8" et redémarré le PC)

**Comment by marsat** [comment]
essai avec 

`aptitude install language-pack-fr `
puis 
LANG=fr_FR.UTF-8 au lieu de LANG=fr_FR.utf8

**Comment by marsat** [comment]
evantuellement 
`sudo dpkg-reconfigure locales`
et cocher la ligne fr_FR.UTF-8 UTF-8

**Comment by ChMaille** [comment]
Bonsoir
J'ai testé les 2 méthodes mais sans succès.

**Comment by marsat** [comment]
je n'est pas réussi a reproduire ton problème , j'ai installer xubuntu17.10 et ubuntu17.10 dans virtualbox et dans les 2 ctparental et bien en françai et une foie que j'ai activer la local es_ES.UTF-8 avec sudo dpkg-reconfigure locales je peut faire la bascule de français a espagnole , si je mais une locales non pris en charge je bascule sur l'anglai.

bref sa semble fonctionner correctement.
éventuellement fais aussi ceci:
sudo rm -f /usr/local/bin/CTparental
puise désinstall ctparental avec la procédure de la [doc](https://doc.ubuntu-fr.org/tutoriel/comment_mettre_en_place_un_controle_parental) et install la toutes dernière version:
https://github.com/marsat/CTparental/releases/download/4.21.03e/ctparental_ubuntu17.xx_4.21.03-1.0_all.deb

**Comment by ChMaille** [comment]
Ça fonctionne, merci !

1. `sudo rm -f /usr/local/bin/CTparental`
2. désinstallation suivant doc
3. nouvelle installation version 4.21.03
