### ISSUE TITLE
Activer le filtrage sur compte admin

### ISSUE THREAD

**Issue by ChMaille** [marsat/CTparental#50]
En tant qu'administrateur du PC familial, mon compte ne subit pas le filtrage DNS lorsque "The preferred Group is currently enabled" (Fonctionnement normal).
Par contre lorsque je désactive "The preferred Group", mon compte ne subit pas le filtrage non plus (fait test ping sur youp***.com).

**Comment by marsat** [comment]
bien c'est le fonctionnement normal les utilisateur faisant partit du group sudo ou root ne subisse pas le filtrage mais ils peuvent  l'activer en paramétrant le proxy 127.0.0.1 port 8080 en http et https dans leur navigateurs.

**Comment by ChMaille** [comment]
OK merci pour l'explication.
Peut-être pourrait-on ajouter un commentaire dans les paramètres à ce sujet avec la méthode pour activer le filtrage sur les utilisateurs appartenant au groupe sudo ou root. Personnellement, je ne sais pas comment faire sous Firefox.
