### ISSUE TITLE
Exportation de la configuration

### ISSUE THREAD

**Issue by ChMaille** [marsat/CTparental#51]
Bonjour.
Avant d'installer chaque nouvelle version sur Ubuntu 17.10 64bit,  je réalise un export de la configuration. Cependant, lorsque je lance la commande `sudo CTparental -exp /home/seb/Documents/` j'ai un message qui me dit `Déjà en cours` alors que je n'ai rien lancé d'autre. Je relance la commande quelques secondes plus tard et cela fonctionne : `Conf exported to /home/seb/Documents/CTparental.conf.18.02.16.tar.gz`

**Comment by marsat** [comment]
c'est normal , c'est une sécurité pour évitée que 2 processus de CTparental soit lancer en me temps, ce qui pourrais provoquer des erreurs car 2 process modifiant en me temps les me fichier de configuration c'est jamais bon, bref.
CTparental étant lancer une fois toute le minute par crontab pour modifier la conf en cas de changement de réseaux (nomadisme du poste) , pour incrémenter les compteur horaire pour les utilisateur ayant de cotas horaires ... ce processus et plus ou moins long ce qui fait que parfois si on lance une commande CTparental il retourne ce message pour indiquer que CTparental et déja en cour d'execution.

**Comment by marsat** [comment]
je vais voir pour trouvai un moyen de faire en sort  de mémorisée les taches a faire dans l'ordre, comme sa , le 2ème processus attendrais la fin du premier avant de ce lancer, mais je voi pas encore comment faire sa, sa viendras sûrement dans une prochaine version.

**Comment by marsat** [comment]
bon je suis arrivée a quelque chose c'est pas parfait mais bon , les prochaine version autoriserons 1 processus en exécution et 1 en attente , le 3eme seras fermer comme dans les précédentes versions.
