### ISSUE TITLE
Gnome extension for CTparental

### ISSUE THREAD

**Issue by madtibo** [marsat/CTparental#52]
Bonjour,

Avec le passage en Debian stretch, les enfants ont perdu les messages quand il ne restait plus que 10 minutes ou moins.
J'ai créé une extension Gnome pour leur présenter le temps restant et les plages horaires de la journée :
https://github.com/madtibo/ctparental-tribu-ml.fr

Par contre, je fonctionne en mode semaine pour le nombre d'heures de connexion, à voir s'il faut mettre quelque chose à jour pour le nombre d'heure par jour...

N'hésitez pas à me remonter tout problème.

Thibaut

**Comment by marsat** [comment]
Merci pour ta contribution .
