### ISSUE TITLE
Problème avec e2guardian.service

### ISSUE THREAD

**Issue by ChMaille** [marsat/CTparental#54]
Lors de l'installation de la version 4.22.01 e2guardian sur Ubuntu 17.10 (64 bits), j'ai eu le retour suivant :

`Paramétrage de e2guardian (3.4.0.3-2) ...`
`Attention ! Le répertoire personnel que vous avez indiqué (/var/log/e2guardian) existe déjà.`
`Ajout de l'utilisateur système « e2guardian » (UID 132) ...`
`Ajout du nouveau groupe « e2guardian » (GID 139) ...`
`Ajout du nouvel utilisateur « e2guardian » (UID 132) avec pour groupe d'appartenance « e2guardian » ...`
`Le répertoire personnel « /var/log/e2guardian » existe déjà.  Rien n'est copié depuis « /etc/skel ».`
`adduser : Attention ! Le répertoire personnel « /var/log/e2guardian » n'appartient pas à l'utilisateur que vous êtes en train de créer.`

`Job for e2guardian.service failed because the control process exited with error code.`
`See "systemctl  status e2guardian.service" and "journalctl  -xe" for details.`
`invoke-rc.d: initscript e2guardian, action "start" failed.`
`● e2guardian.service - E2guardian Web filtering`
`   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)`
`   Active: failed (Result: exit-code) since Thu 2018-04-19 15:12:04 CEST; 12ms ago`
`     Docs: http://e2guardian.org/`
`  Process: 12406 ExecStart=/usr/sbin/e2guardian (code=exited, status=1/FAILURE)`
` Main PID: 3245 (code=exited, status=0/SUCCESS)`

`avril 19 15:12:04 Seb-Ubuntu systemd[1]: Starting E2guardian Web filtering...`
`avril 19 15:12:04 Seb-Ubuntu e2guardian[12406]: Error binding ipc server file (try using the SysV to stop e2guardian then try starting it again or doing an 'rm /tmp/.e2guardianipc').`
`avril 19 15:12:04 Seb-Ubuntu e2guardian[12406]: Exiting with error`
`avril 19 15:12:04 Seb-Ubuntu systemd[1]: e2guardian.service: Control process exited, code=exited status=1`
`avril 19 15:12:04 Seb-Ubuntu systemd[1]: Failed to start E2guardian Web filtering.`
`avril 19 15:12:04 Seb-Ubuntu systemd[1]: e2guardian.service: Unit entered failed state.`
`avril 19 15:12:04 Seb-Ubuntu systemd[1]: e2guardian.service: Failed with result 'exit-code'.`
`WARNING: Starting e2guardian failed. Please check your configuration.`

**Comment by marsat** [comment]
le problème semble arrivé pendent l’installe du paqué e2guardian avant me que ctparental commence, a tu bien fait ceci avant:
`sudo apt-get autoremove --purge ctparental clamav-* privoxy e2guardian dnsmasq`
`sudo rm -rf /etc/CTparental`
plusieurs erreurs indicant le fichier de log /var/log/e2guardian  , donc après la ligne ci dessus et avant de réinstaller ctparental fait ceci:
`rm -rf  /var/log/e2guardian`

la version 4.22.01  avait encore quelque bug , réinstalle plutôt celle-ci.
https://github.com/marsat/CTparental/releases/download/4.22.02/ctparental_debian9_ubuntu17xx_4.22.02-1.0_all.deb

**Comment by marsat** [comment]
Super effectivement rien de bien méchant dans le retour.
n’hésite pas a refaire des remontée en cas de problèmes.

**Comment by ChMaille** [comment]
OK, ça marche.
L'origine du problème avec le fichier 'pkcs11.txt c'est que le script ne le cherche pas dans le bon dossier. J'en ai 2 dans mon répertoire utilisateur :

- '/home/seb/.mozilla/firefox/ut488pmz.default-1516806555345/'
- '/home/seb/.mozilla/firefox/124n5al2.default/'

Le fichier 'pkcs11.txt' est dans le premier dossier.
