### ISSUE TITLE
Acces distant à l'interface Web

### ISSUE THREAD

**Issue by mathieuleon** [marsat/CTparental#55]
Bonjour,

Auparavant, j'utilisais une ancienne version de CTparental et je pouvais administrer le PC de mes enfants via mon PC en me connectant à l'interface Web.
Avec la nouvelle version, ce fonctionnement n'est plus possible. Je suis obligé d'aller sur l'ordinateur de mes enfants pour administrer. Est-il possible d'activer à nouveau cet accès distant ?

Autres remarque: j'ai aussi rencontré le problème lighttp et en installant le paquet gamin (https://github.com/marsat/CTparental/issues/41), ça marche.

**Comment by marsat** [comment]
Bonjour,

par défaut CTparental na jamais étais administrable a distance carre lighttpd n'écouter que sur 127.0.0.10 et 127.0.0.11, les dernière version, apport une fonctionnalité client serveur c'est a dire que tu peut paramétrer ton poste  en serveur avec la commande suivante:

`sudo CTparental -srvon`
ATTENTION si tu utiliser un serveur SSH sur ton poste fait une sauvegarde de sa configuration avant, car le serveur ctparental et basé sur ssh et écrase la conf serveur ssh, a l'éxecution de la commande `sudo CTparental -srvon`

une foie ceci fait quant tu vas sur l’interface d'administration de ton poste tu devrais avoir quelque chause comme ceci en haut

> Server on, launch this command on the client to join it.
> CTparental -syncon "fe80::aaaa:bbbb:cccc:dddd" "PaSWorD" "22"
> Le filtrage de noms de domaine est actuellement activé 

par la suite si tu veut que l'un des pc de la maison ce synchronise avec ton poste, tu n'a cas lancer la commande indiquer en root ou avec sudo sur les poste clients (pc des enfants).
> CTparental -syncon "fe80::aaaa:bbbb:cccc:dddd" "PaSWorD" "22"

après sa sur l'interface admin du poste client tu doit voir ceci:
> Synchronized client on ipv6. fe80::aaaa:bbbb:cccc:dddd
cette manipulation et a faire une seul foie par poste clients. après tous et automatique tu modifie ta conf sur ton poste et celle si et automatiquement distribuer sur les clients dans les 30 minutes

si tu veut pouvoir gérer leur heure de connexion il faut créer sur ton poste des les même utilisateur que sur leur postes, bien sur tu n'est pas obliger de mètre le me mot de passe si tu ne veut pas qu'il ce connecte a ton poste.

je te conseille d'utilisée la version 4.22.03 e2guardian sur touts les postes de la maison pour que cela fonctionne.

il faut conter entre 20 et 30 minute pour qu'un changement de confe sur le serveur ce propage sur les clients, on peut le forcer en lancer `sudo CTparental -expsync` sur le server
puis sur les clients  `sudo CTparental  -csync`

j’espère être suffisamment claire .

cordialement

**Comment by mathieuleon** [comment]
Merci.
Si je comprends bien, je dois installer CTparental sur mon pc perso en plus de celui des enfants. J'administre sur mon poste et je synchronise avec celui des enfants.
C'est pas vraiment ce que je recherche mais ça me va.
Pour info, avec la version 4.18, j'arrivais à me connecter sur l'interface d'administration de CTparental à distance (réseau local)

**Comment by marsat** [comment]
mais tu peut si tu veut vraiment rendre accessible l'interface sur ton réseau local, édit le fichier 
/etc/lighttpd/conf-enabled/10-CTparental.conf
et ajoute les ligne suivantes a la fin en remplacent toute les occurrences de 192.168.1.2 par l'ip de la carte réseau  du poste. bien sur cela ne marchera que si tu fix les ip des poste ou tu veut prendre la mains a distance .
```
$HTTP["host"] =~ "192.168.1.2" {
        auth.require = ( "" =>
                   (
                     "method"  => "digest",
                     "realm"   => "interface admin",
                     "require" => "user=admin"
                   )
                 )
        server.document-root = "/var/www/CTadmin"
        $SERVER["socket"] == "192.168.1.2:80" {
        url.redirect  = (".*" => "https://192.168.18.2$0" )
        }

        $SERVER["socket"] == "192.168.1.2:443" {
        ssl.engine = "enable"
        ssl.pemfile = "/etc/ssl/private/ct.local.pem"
        }
}
```
puis redémarrer le service lighttpd pour que cela soit prit en compte 
`sudo service lighttpd restart`
