### ISSUE TITLE
erreur quand l'utilisateur a moins de 5 lettres

### ISSUE THREAD

**Issue by benfonty** [marsat/CTparental#56]
Bonjour,

Quand j'essaie d'installer la dernière version de ctparental et que mon utilisateur a moins de 5 lettres, j'ai l'erreur suivante en fin d'installation au lieu du message d'erreur prévu et de la possibilité de ressaisir l'utilisateur :

> dpkg: erreur de traitement du paquet ctparental (--install) :
>  installed ctparental package post-installation script subprocess returned error exit status 1
> Traitement des actions différées (« triggers ») pour man-db (2.8.3-2) ...
> Des erreurs ont été rencontrées pendant l'exécution :
>  ctparental

**Comment by marsat** [comment]
sur quel distribution

**Comment by marsat** [comment]
problème résolut dans la https://github.com/marsat/CTparental/releases/download/4.22.07e/ctparental_debian9_ubuntu17.xx_18.04_4.22.07-1.0_all.deb
du moins sur ma debian9  et lubuntu 18.04

**Comment by benfonty** [comment]
Je confirme et clôture.
